//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/canvas/LayerCanvas.java
//
//  Created by Thomas on 7/1/13.
//

@protocol PlaynCoreCanvas;
@protocol PlaynCoreInternalTransform;

#import "JreEmulation.h"
#import "playn/core/AbstractLayer.h"

@interface PlaynCoreCanvasLayerCanvas : PlaynCoreAbstractLayer {
}

- (void)paintWithPlaynCoreCanvas:(id<PlaynCoreCanvas>)canvas
                       withFloat:(float)parentAlpha;
- (id)initWithPlaynCoreInternalTransform:(id<PlaynCoreInternalTransform>)xform;
- (void)transformWithPlaynCoreCanvas:(id<PlaynCoreCanvas>)canvas;
@end
