//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/ui/bgs/ImageBackground.java
//
//  Created by Thomas on 7/1/13.
//

@class TripleplayUiBackground_Instance;
@protocol PlaynCoreImage;
@protocol PythagorasFIDimension;

#import "JreEmulation.h"
#import "Background.h"

@interface TripleplayUiBgsImageBackground : TripleplayUiBackground {
 @public
  id<PlaynCoreImage> _image_;
}

@property (nonatomic, retain) id<PlaynCoreImage> _image;

- (id)initWithPlaynCoreImage:(id<PlaynCoreImage>)image;
- (TripleplayUiBackground_Instance *)instantiateWithPythagorasFIDimension:(id<PythagorasFIDimension>)size;
@end
