//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/ui/bgs/SolidBackground.java
//
//  Created by Thomas on 7/1/13.
//

#import "Background.h"
#import "IDimension.h"
#import "IOSObjectArray.h"
#import "Layer.h"

@implementation TripleplayUiBgsSolidBackground

@synthesize _color = _color_;

- (id)initWithInt:(int)color {
  if ((self = [super init])) {
    _color_ = color;
  }
  return self;
}

- (TripleplayUiBackground_Instance *)instantiateWithPythagorasFIDimension:(id<PythagorasFIDimension>)size {
  return [[[TripleplayUiBackground_LayerInstance alloc] initWithTripleplayUiBackground:self withPythagorasFIDimension:size withPlaynCoreLayerArray:[IOSObjectArray arrayWithType:[IOSClass classWithProtocol:@protocol(PlaynCoreLayer)] count:1, [self createSolidLayerWithInt:_color_ withFloat:[((id<PythagorasFIDimension>) NIL_CHK(size)) width] withFloat:[((id<PythagorasFIDimension>) NIL_CHK(size)) height]] ]] autorelease];
}

- (void)dealloc {
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TripleplayUiBgsSolidBackground *typedCopy = (TripleplayUiBgsSolidBackground *) copy;
  typedCopy._color = _color_;
}

@end
