//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/StockInternalTransform.java
//
//  Created by Thomas on 7/1/13.
//

@protocol PythagorasFTransform;

#import "JreEmulation.h"
#import "playn/core/InternalTransform.h"
#import "pythagoras/f/AffineTransform.h"

@interface PlaynCoreStockInternalTransform : PythagorasFAffineTransform < PlaynCoreInternalTransform > {
}

+ (PlaynCoreStockInternalTransform *)IDENTITY;
- (id)init;
- (id)initWithFloat:(float)m00
          withFloat:(float)m01
          withFloat:(float)m10
          withFloat:(float)m11
          withFloat:(float)tx
          withFloat:(float)ty;
- (float)m00;
- (float)m01;
- (float)m10;
- (float)m11;
- (id<PlaynCoreInternalTransform>)setWithPythagorasFTransform:(id<PythagorasFTransform>)other;
- (id<PlaynCoreInternalTransform>)concatenateWithPythagorasFTransform:(id<PythagorasFTransform>)other
                                                            withFloat:(float)originX
                                                            withFloat:(float)originY;
- (id<PlaynCoreInternalTransform>)concatenateWithFloat:(float)m00
                                             withFloat:(float)m01
                                             withFloat:(float)m10
                                             withFloat:(float)m11
                                             withFloat:(float)tx
                                             withFloat:(float)ty
                                             withFloat:(float)originX
                                             withFloat:(float)originY;
- (id<PlaynCoreInternalTransform>)preConcatenateWithPlaynCoreInternalTransform:(id<PlaynCoreInternalTransform>)other;
- (id<PlaynCoreInternalTransform>)copy__ OBJC_METHOD_FAMILY_NONE;
@end
