//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/Surface.java
//
//  Created by Thomas on 7/1/13.
//

@class IOSFloatArray;
@class IOSIntArray;
@class PlaynCoreGlGLShader;
@protocol PlaynCoreImage;
@protocol PlaynCoreLayer;
@protocol PlaynCorePattern;

#import "JreEmulation.h"

@protocol PlaynCoreSurface < NSObject >
- (float)width;
- (float)height;
- (id<PlaynCoreSurface>)save;
- (id<PlaynCoreSurface>)restore;
- (id<PlaynCoreSurface>)translateWithFloat:(float)x
                                 withFloat:(float)y;
- (id<PlaynCoreSurface>)scale__WithFloat:(float)sx
                               withFloat:(float)sy;
- (id<PlaynCoreSurface>)rotateWithFloat:(float)radians;
- (id<PlaynCoreSurface>)transformWithFloat:(float)m11
                                 withFloat:(float)m12
                                 withFloat:(float)m21
                                 withFloat:(float)m22
                                 withFloat:(float)dx
                                 withFloat:(float)dy;
- (id<PlaynCoreSurface>)setTransformWithFloat:(float)m11
                                    withFloat:(float)m12
                                    withFloat:(float)m21
                                    withFloat:(float)m22
                                    withFloat:(float)dx
                                    withFloat:(float)dy;
- (id<PlaynCoreSurface>)setAlphaWithFloat:(float)alpha;
- (id<PlaynCoreSurface>)setTintWithInt:(int)tint;
- (id<PlaynCoreSurface>)setFillColorWithInt:(int)color;
- (id<PlaynCoreSurface>)setFillPatternWithPlaynCorePattern:(id<PlaynCorePattern>)pattern;
- (id<PlaynCoreSurface>)setShaderWithPlaynCoreGlGLShader:(PlaynCoreGlGLShader *)shader;
- (id<PlaynCoreSurface>)clear;
- (id<PlaynCoreSurface>)drawImageWithPlaynCoreImage:(id<PlaynCoreImage>)image
                                          withFloat:(float)dx
                                          withFloat:(float)dy;
- (id<PlaynCoreSurface>)drawImageWithPlaynCoreImage:(id<PlaynCoreImage>)image
                                          withFloat:(float)dx
                                          withFloat:(float)dy
                                          withFloat:(float)dw
                                          withFloat:(float)dh;
- (id<PlaynCoreSurface>)drawImageWithPlaynCoreImage:(id<PlaynCoreImage>)image
                                          withFloat:(float)dx
                                          withFloat:(float)dy
                                          withFloat:(float)dw
                                          withFloat:(float)dh
                                          withFloat:(float)sx
                                          withFloat:(float)sy
                                          withFloat:(float)sw
                                          withFloat:(float)sh;
- (id<PlaynCoreSurface>)drawImageCenteredWithPlaynCoreImage:(id<PlaynCoreImage>)image
                                                  withFloat:(float)dx
                                                  withFloat:(float)dy;
- (id<PlaynCoreSurface>)drawLineWithFloat:(float)x0
                                withFloat:(float)y0
                                withFloat:(float)x1
                                withFloat:(float)y1
                                withFloat:(float)width;
- (id<PlaynCoreSurface>)drawLayerWithPlaynCoreLayer:(id<PlaynCoreLayer>)layer;
- (id<PlaynCoreSurface>)fillRectWithFloat:(float)x
                                withFloat:(float)y
                                withFloat:(float)width
                                withFloat:(float)height;
- (id<PlaynCoreSurface>)fillTrianglesWithJavaLangFloatArray:(IOSFloatArray *)xys
                                   withJavaLangIntegerArray:(IOSIntArray *)indices;
- (id<PlaynCoreSurface>)fillTrianglesWithJavaLangFloatArray:(IOSFloatArray *)xys
                                     withJavaLangFloatArray:(IOSFloatArray *)sxys
                                   withJavaLangIntegerArray:(IOSIntArray *)indices;
@end
