//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/f/AbstractRoundRectangle.java
//
//  Created by Thomas on 7/1/13.
//

@class IOSFloatArray;
@class IOSIntArray;
@class IOSObjectArray;
@class PythagorasFRoundRectangle;
@protocol PythagorasFTransform;

#import "JreEmulation.h"
#import "pythagoras/f/IRoundRectangle.h"
#import "pythagoras/f/PathIterator.h"
#import "pythagoras/f/RectangularShape.h"

@interface PythagorasFAbstractRoundRectangle : PythagorasFRectangularShape < PythagorasFIRoundRectangle > {
}

+ (IOSIntArray *)TYPES;
+ (float)U;
+ (IOSObjectArray *)POINTS;
- (PythagorasFRoundRectangle *)clone;
- (BOOL)containsWithFloat:(float)px
                withFloat:(float)py;
- (BOOL)containsWithFloat:(float)rx
                withFloat:(float)ry
                withFloat:(float)rw
                withFloat:(float)rh;
- (BOOL)intersectsWithFloat:(float)rx
                  withFloat:(float)ry
                  withFloat:(float)rw
                  withFloat:(float)rh;
- (id<PythagorasFPathIterator>)pathIteratorWithPythagorasFTransform:(id<PythagorasFTransform>)at;
- (float)arcHeight;
- (float)arcWidth;
- (float)height;
- (float)width;
- (float)x;
- (float)y;
- (id)init;
- (id)copyWithZone:(NSZone *)zone;
@end

@interface PythagorasFAbstractRoundRectangle_Iterator : NSObject < PythagorasFPathIterator > {
 @public
  float x_, y_, width_, height_, aw_, ah_;
  id<PythagorasFTransform> t_;
  int index_;
}

@property (nonatomic, assign) float x;
@property (nonatomic, assign) float y;
@property (nonatomic, assign) float width;
@property (nonatomic, assign) float height;
@property (nonatomic, assign) float aw;
@property (nonatomic, assign) float ah;
@property (nonatomic, retain) id<PythagorasFTransform> t;
@property (nonatomic, assign) int index;

- (id)initWithPythagorasFIRoundRectangle:(id<PythagorasFIRoundRectangle>)rr
                withPythagorasFTransform:(id<PythagorasFTransform>)at;
- (int)windingRule;
- (BOOL)isDone;
- (void)next;
- (int)currentSegmentWithJavaLangFloatArray:(IOSFloatArray *)coords;
@end
