//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: C:\Users\Thomas\Documents\Eclipse\Tux\tuxblocks\core\src\main\java\tuxkids\tuxblocks\core\defense\tower\PeaShooter.java
//
//  Created by Thomas on 7/1/13.
//

#import "tuxkids/tuxblocks/core/defense/projectile/Pea.h"
#import "tuxkids/tuxblocks/core/defense/projectile/Projectile.h"
#import "tuxkids/tuxblocks/core/defense/tower/PeaShooter.h"
#import "tuxkids/tuxblocks/core/defense/tower/Tower.h"

@implementation TBPeaShooter

- (int)rows {
  return 1;
}

- (int)cols {
  return 1;
}

- (float)damage {
  return 1;
}

- (int)fireRate {
  return 500;
}

- (float)range {
  return 5;
}

- (TBProjectile *)createProjectile {
  return [[[TBPea alloc] init] autorelease];
}

- (TBTower *)copy__ OBJC_METHOD_FAMILY_NONE {
  return [[[TBPeaShooter alloc] init] autorelease];
}

- (NSString *)name {
  return @"Pea Shooter";
}

- (int)cost {
  return 1;
}

- (int)commonness {
  return 5;
}

- (id)init {
  return [super init];
}

- (void)dealloc {
  [super dealloc];
}

@end
