//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: C:\Users\Thomas\Documents\Eclipse\Tux\tuxblocks\core\src\main\java\tuxkids\tuxblocks\core\defense\tower\Tower.java
//
//  Created by Thomas on 7/1/13.
//

@class PythagorasFVector;
@class PythagorasIPoint;
@class TBDGrid;
@class TBImageLayerTintable;
@class TBProjectile;
@class TBTowerTypeEnum;
@class TBWalker;
@protocol JavaUtilList;
@protocol PlaynCoreImage;
@protocol PlaynCoreLayer;
@protocol PlaynCoreUtilClock;

#import "JreEmulation.h"
#import "tuxkids/tuxblocks/core/defense/DiscreteGridObject.h"

@interface TBTower : TBDDiscreteGridObject {
 @public
  TBImageLayerTintable *layer__;
  int fireTimer_;
  PythagorasFVector *position__;
  int id__;
  TBWalker *lastTarget__;
}

@property (nonatomic, retain) TBImageLayerTintable *layer_;
@property (nonatomic, assign) int fireTimer;
@property (nonatomic, retain) PythagorasFVector *position_;
@property (nonatomic, assign) int id_;
@property (nonatomic, retain) TBWalker *lastTarget_;

+ (id<JavaUtilList>)towerBag;
- (int)rows;
- (int)cols;
- (float)damage;
- (int)fireRate;
- (float)range;
- (TBProjectile *)createProjectile;
- (TBTower *)copy__ OBJC_METHOD_FAMILY_NONE;
- (NSString *)name;
- (int)cost;
- (int)commonness;
+ (TBTowerTypeEnum *)getTypeByIndexWithInt:(int)index;
- (float)splashRadius;
- (float)baseWidth;
- (float)baseHeight;
- (float)width;
- (float)height;
- (TBImageLayerTintable *)layer;
- (id<PlaynCoreLayer>)layerAddable;
- (PythagorasFVector *)position;
- (PythagorasFVector *)projectileStart;
- (int)id__;
+ (TBTowerTypeEnum *)randomTower;
+ (int)towerCount;
- (void)addBuffsWithTBWalker:(TBWalker *)walker;
- (TBWalker *)lastTarget;
- (void)setLastTargetWithTBWalker:(TBWalker *)target;
- (void)setCoordinatesWithPythagorasIPoint:(PythagorasIPoint *)coordinates;
- (void)setCoordinatesWithInt:(int)row
                      withInt:(int)col;
- (void)setDepthWithFloat:(float)depth;
- (TBTower *)previewWithTBDGrid:(TBDGrid *)grid;
- (TBTower *)placeWithTBDGrid:(TBDGrid *)grid
         withPythagorasIPoint:(PythagorasIPoint *)coordinates;
- (BOOL)updateWithInt:(int)delta;
- (void)paintWithPlaynCoreUtilClock:(id<PlaynCoreUtilClock>)clock;
- (BOOL)fire;
- (BOOL)canPlaceWithInt:(int)row
                withInt:(int)col;
- (id<PlaynCoreImage>)createRadiusImage;
- (id<PlaynCoreImage>)createImageWithFloat:(float)cellSize
                                   withInt:(int)color;
- (id)init;
@end

typedef TBTower TuxkidsTuxblocksCoreDefenseTowerTower;
