package tuxkids.tuxblocks.core.student;

public enum ActionType{
	 ADD_INTEGERS, SUBTRACT_INTEGERS, MULTIPLY_INTEGERS_LOW,MULTIPLY_INTEGERS_MED,MULTIPLY_INTEGERS_HIGH,
	 DIVIDE_INTEGERS_LOW,DIVIDE_INTEGERS_MED,DIVIDE_INTEGERS_HIGH, 
	 
	 COMBINE_UNKNOWNS,
	 
	 ADD_EQUATION_SIDES, SUBTRACT_EQUATION_SIDES, MULTIPLY_SINGLE_SIDE, MULTIPLY_MULTIPLE_SIDES,
	 DIVIDE_SINGLE_SIDE, DIVIDE_MULTIPLE_SIDES, 
	 
	 SIMPLIFY_LIKE_FACTORS, SIMPLIFY_DIFFERENT_FACTORS, SIMPLIFY_ADDENS,
	 CANCEL_FACTORS, CANCEL_ADDENS,
	 
	 DISTRIBUTION, COMBINATION,
	 
	 BUILDING_SYMBOLIC_EQUATIONS, BUILDING_WRITTEN_EQUATIONS
}