//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/particle/init/Transform.java
//
//  Created by Thomas on 7/1/13.
//

#import "FloatMath.h"
#import "GLContext.h"
#import "Graphics.h"
#import "GroupLayer.h"
#import "IOSFloatArray.h"
#import "Initializer.h"
#import "InternalTransform.h"
#import "Layer.h"
#import "ParticleBuffer.h"
#import "PlayN.h"
#import "Randoms.h"
#import "Transform.h"
#import "java/lang/System.h"

@implementation TripleplayParticleInitTransform

+ (TPInitializer *)identity {
  return [TripleplayParticleInitTransform constantWithFloat:0 withFloat:0];
}

+ (TPInitializer *)constantWithFloat:(float)tx
                           withFloat:(float)ty {
  return [TripleplayParticleInitTransform constantWithFloat:1 withFloat:0 withFloat:tx withFloat:ty];
}

+ (TPInitializer *)constantWithFloat:(float)scale_
                           withFloat:(float)rot
                           withFloat:(float)tx
                           withFloat:(float)ty {
  float sina = [PythagorasFFloatMath sinWithFloat:rot], cosa = [PythagorasFFloatMath cosWithFloat:rot];
  float m00 = cosa * scale_, m01 = sina * scale_, m10 = -sina * scale_, m11 = cosa * scale_;
  return [[[TripleplayParticleInitTransform_$1 alloc] initWithFloat:m00 withFloat:m01 withFloat:m10 withFloat:m11 withFloat:tx withFloat:ty] autorelease];
}

+ (TPInitializer *)scale__WithFloat:(float)scale_ {
  return [[[TripleplayParticleInitTransform_$2 alloc] initWithFloat:scale_] autorelease];
}

+ (TPInitializer *)randomScaleWithTripleplayUtilRandoms:(TripleplayUtilRandoms *)rando
                                              withFloat:(float)minScale
                                              withFloat:(float)maxScale {
  return [[[TripleplayParticleInitTransform_$3 alloc] initWithTripleplayUtilRandoms:rando withFloat:minScale withFloat:maxScale] autorelease];
}

+ (TPInitializer *)layerWithPlaynCoreLayer:(id<PlaynCoreLayer>)layer {
  return [[[TripleplayParticleInitTransform_$4 alloc] initWithPlaynCoreLayer:layer] autorelease];
}

+ (TPInitializer *)randomPosWithTripleplayUtilRandoms:(TripleplayUtilRandoms *)rando
                                            withFloat:(float)x
                                            withFloat:(float)y
                                            withFloat:(float)width
                                            withFloat:(float)height {
  return [[[TripleplayParticleInitTransform_$5 alloc] initWithFloat:x withTripleplayUtilRandoms:rando withFloat:width withFloat:y withFloat:height] autorelease];
}

+ (TPInitializer *)randomOffsetWithTripleplayUtilRandoms:(TripleplayUtilRandoms *)rando
                                               withFloat:(float)noise {
  return [[[TripleplayParticleInitTransform_$6 alloc] initWithTripleplayUtilRandoms:rando withFloat:noise] autorelease];
}

- (id)init {
  return [super init];
}

- (void)dealloc {
  [super dealloc];
}

@end
@implementation TripleplayParticleInitTransform_$1

@synthesize val$m00 = val$m00_;
@synthesize val$m01 = val$m01_;
@synthesize val$m10 = val$m10_;
@synthesize val$m11 = val$m11_;
@synthesize val$tx = val$tx_;
@synthesize val$ty = val$ty_;

- (void)init__WithInt:(int)index
withJavaLangFloatArray:(IOSFloatArray *)data
              withInt:(int)start OBJC_METHOD_FAMILY_NONE {
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_M00 withFloat:val$m00_];
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_M01 withFloat:val$m01_];
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_M10 withFloat:val$m10_];
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_M11 withFloat:val$m11_];
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_TX withFloat:val$tx_];
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_TY withFloat:val$ty_];
}

- (id)initWithFloat:(float)capture$0
          withFloat:(float)capture$1
          withFloat:(float)capture$2
          withFloat:(float)capture$3
          withFloat:(float)capture$4
          withFloat:(float)capture$5 {
  if ((self = [super init])) {
    val$m00_ = capture$0;
    val$m01_ = capture$1;
    val$m10_ = capture$2;
    val$m11_ = capture$3;
    val$tx_ = capture$4;
    val$ty_ = capture$5;
  }
  return self;
}

- (void)dealloc {
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TripleplayParticleInitTransform_$1 *typedCopy = (TripleplayParticleInitTransform_$1 *) copy;
  typedCopy.val$m00 = val$m00_;
  typedCopy.val$m01 = val$m01_;
  typedCopy.val$m10 = val$m10_;
  typedCopy.val$m11 = val$m11_;
  typedCopy.val$tx = val$tx_;
  typedCopy.val$ty = val$ty_;
}

@end
@implementation TripleplayParticleInitTransform_$2

@synthesize val$scale = val$scale_;

- (void)init__WithInt:(int)index
withJavaLangFloatArray:(IOSFloatArray *)data
              withInt:(int)start OBJC_METHOD_FAMILY_NONE {
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_M00 withFloat:[data floatAtIndex:start + TPParticleBuffer_M00] * val$scale_];
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_M01 withFloat:[data floatAtIndex:start + TPParticleBuffer_M01] * val$scale_];
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_M10 withFloat:[data floatAtIndex:start + TPParticleBuffer_M10] * val$scale_];
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_M11 withFloat:[data floatAtIndex:start + TPParticleBuffer_M11] * val$scale_];
}

- (id)initWithFloat:(float)capture$0 {
  if ((self = [super init])) {
    val$scale_ = capture$0;
  }
  return self;
}

- (void)dealloc {
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TripleplayParticleInitTransform_$2 *typedCopy = (TripleplayParticleInitTransform_$2 *) copy;
  typedCopy.val$scale = val$scale_;
}

@end
@implementation TripleplayParticleInitTransform_$3

- (TripleplayUtilRandoms *)val$rando {
  return val$rando_;
}
- (void)setVal$rando:(TripleplayUtilRandoms *)val$rando {
  JreOperatorRetainedAssign(&val$rando_, self, val$rando);
}
@synthesize val$rando = val$rando_;
@synthesize val$minScale = val$minScale_;
@synthesize val$maxScale = val$maxScale_;

- (void)init__WithInt:(int)index
withJavaLangFloatArray:(IOSFloatArray *)data
              withInt:(int)start OBJC_METHOD_FAMILY_NONE {
  float scale_ = [((TripleplayUtilRandoms *) NIL_CHK(val$rando_)) getInRangeWithFloat:val$minScale_ withFloat:val$maxScale_];
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_M00 withFloat:[data floatAtIndex:start + TPParticleBuffer_M00] * scale_];
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_M01 withFloat:[data floatAtIndex:start + TPParticleBuffer_M01] * scale_];
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_M10 withFloat:[data floatAtIndex:start + TPParticleBuffer_M10] * scale_];
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_M11 withFloat:[data floatAtIndex:start + TPParticleBuffer_M11] * scale_];
}

- (id)initWithTripleplayUtilRandoms:(TripleplayUtilRandoms *)capture$0
                          withFloat:(float)capture$1
                          withFloat:(float)capture$2 {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&val$rando_, self, capture$0);
    val$minScale_ = capture$1;
    val$maxScale_ = capture$2;
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&val$rando_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TripleplayParticleInitTransform_$3 *typedCopy = (TripleplayParticleInitTransform_$3 *) copy;
  typedCopy.val$rando = val$rando_;
  typedCopy.val$minScale = val$minScale_;
  typedCopy.val$maxScale = val$maxScale_;
}

@end
@implementation TripleplayParticleInitTransform_$4

- (id<PlaynCoreInternalTransform>)xform {
  return xform_;
}
- (void)setXform:(id<PlaynCoreInternalTransform>)xform {
  JreOperatorRetainedAssign(&xform_, self, xform);
}
@synthesize xform = xform_;
- (IOSFloatArray *)_matrix {
  return _matrix_;
}
- (void)set_matrix:(IOSFloatArray *)_matrix {
  JreOperatorRetainedAssign(&_matrix_, self, _matrix);
}
@synthesize _matrix = _matrix_;
- (id<PlaynCoreLayer>)val$layer {
  return val$layer_;
}
- (void)setVal$layer:(id<PlaynCoreLayer>)val$layer {
  JreOperatorRetainedAssign(&val$layer_, self, val$layer);
}
@synthesize val$layer = val$layer_;

- (void)willInitWithInt:(int)count {
  (void) [((id<PlaynCoreInternalTransform>) NIL_CHK(xform_)) setTransformWithFloat:1 withFloat:0 withFloat:0 withFloat:1 withFloat:0 withFloat:0];
  id<PlaynCoreLayer> xlayer = val$layer_;
  while (xlayer != nil) {
    (void) [((id<PlaynCoreInternalTransform>) NIL_CHK(xform_)) preConcatenateWithPlaynCoreInternalTransform:(id<PlaynCoreInternalTransform>) [((id<PlaynCoreLayer>) NIL_CHK(xlayer)) transform]];
    xlayer = [((id<PlaynCoreLayer>) NIL_CHK(xlayer)) parent];
  }
  (void) [((id<PlaynCoreInternalTransform>) NIL_CHK(xform_)) preConcatenateWithPlaynCoreInternalTransform:[[((id<PlaynCoreGraphics>) [PlaynCorePlayN graphics]) ctx] rootTransform]];
  [((id<PlaynCoreInternalTransform>) NIL_CHK(xform_)) getWithJavaLangFloatArray:_matrix_];
}

- (void)init__WithInt:(int)index
withJavaLangFloatArray:(IOSFloatArray *)data
              withInt:(int)start OBJC_METHOD_FAMILY_NONE {
  [JavaLangSystem arraycopyWithId:_matrix_ withInt:0 withId:data withInt:start + TPParticleBuffer_M00 withInt:6];
}

- (id)initWithPlaynCoreLayer:(id<PlaynCoreLayer>)capture$0 {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&val$layer_, self, capture$0);
    JreOperatorRetainedAssign(&xform_, self, [[((id<PlaynCoreGraphics>) [PlaynCorePlayN graphics]) ctx] createTransform]);
    JreOperatorRetainedAssign(&_matrix_, self, [[[IOSFloatArray alloc] initWithLength:6] autorelease]);
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&val$layer_, self, nil);
  JreOperatorRetainedAssign(&_matrix_, self, nil);
  JreOperatorRetainedAssign(&xform_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TripleplayParticleInitTransform_$4 *typedCopy = (TripleplayParticleInitTransform_$4 *) copy;
  typedCopy.xform = xform_;
  typedCopy._matrix = _matrix_;
  typedCopy.val$layer = val$layer_;
}

@end
@implementation TripleplayParticleInitTransform_$5

@synthesize val$x = val$x_;
- (TripleplayUtilRandoms *)val$rando {
  return val$rando_;
}
- (void)setVal$rando:(TripleplayUtilRandoms *)val$rando {
  JreOperatorRetainedAssign(&val$rando_, self, val$rando);
}
@synthesize val$rando = val$rando_;
@synthesize val$width = val$width_;
@synthesize val$y = val$y_;
@synthesize val$height = val$height_;

- (void)init__WithInt:(int)index
withJavaLangFloatArray:(IOSFloatArray *)data
              withInt:(int)start OBJC_METHOD_FAMILY_NONE {
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_TX withFloat:val$x_ + [((TripleplayUtilRandoms *) NIL_CHK(val$rando_)) getFloatWithFloat:val$width_]];
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_TY withFloat:val$y_ + [((TripleplayUtilRandoms *) NIL_CHK(val$rando_)) getFloatWithFloat:val$height_]];
}

- (id)initWithFloat:(float)capture$0
withTripleplayUtilRandoms:(TripleplayUtilRandoms *)capture$1
          withFloat:(float)capture$2
          withFloat:(float)capture$3
          withFloat:(float)capture$4 {
  if ((self = [super init])) {
    val$x_ = capture$0;
    JreOperatorRetainedAssign(&val$rando_, self, capture$1);
    val$width_ = capture$2;
    val$y_ = capture$3;
    val$height_ = capture$4;
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&val$rando_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TripleplayParticleInitTransform_$5 *typedCopy = (TripleplayParticleInitTransform_$5 *) copy;
  typedCopy.val$x = val$x_;
  typedCopy.val$rando = val$rando_;
  typedCopy.val$width = val$width_;
  typedCopy.val$y = val$y_;
  typedCopy.val$height = val$height_;
}

@end
@implementation TripleplayParticleInitTransform_$6

- (TripleplayUtilRandoms *)val$rando {
  return val$rando_;
}
- (void)setVal$rando:(TripleplayUtilRandoms *)val$rando {
  JreOperatorRetainedAssign(&val$rando_, self, val$rando);
}
@synthesize val$rando = val$rando_;
@synthesize val$noise = val$noise_;

- (void)init__WithInt:(int)index
withJavaLangFloatArray:(IOSFloatArray *)data
              withInt:(int)start OBJC_METHOD_FAMILY_NONE {
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_TX withFloat:[data floatAtIndex:start + TPParticleBuffer_TX] + [((TripleplayUtilRandoms *) NIL_CHK(val$rando_)) getInRangeWithFloat:-val$noise_ withFloat:val$noise_]];
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_TY withFloat:[data floatAtIndex:start + TPParticleBuffer_TY] + [((TripleplayUtilRandoms *) NIL_CHK(val$rando_)) getInRangeWithFloat:-val$noise_ withFloat:val$noise_]];
}

- (id)initWithTripleplayUtilRandoms:(TripleplayUtilRandoms *)capture$0
                          withFloat:(float)capture$1 {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&val$rando_, self, capture$0);
    val$noise_ = capture$1;
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&val$rando_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TripleplayParticleInitTransform_$6 *typedCopy = (TripleplayParticleInitTransform_$6 *) copy;
  typedCopy.val$rando = val$rando_;
  typedCopy.val$noise = val$noise_;
}

@end
