//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/d/FlatteningPathIterator.java
//
//  Created by Thomas on 7/9/13.
//

#import "IOSDoubleArray.h"
#import "java/lang/IllegalArgumentException.h"
#import "java/lang/Math.h"
#import "java/lang/NullPointerException.h"
#import "java/lang/System.h"
#import "java/util/NoSuchElementException.h"
#import "pythagoras/d/CubicCurves.h"
#import "pythagoras/d/PathIterator.h"
#import "pythagoras/d/QuadCurves.h"

@implementation PythagorasDFlatteningPathIterator

@synthesize bufType = bufType_;
@synthesize bufLimit = bufLimit_;
@synthesize bufSize = bufSize_;
@synthesize bufIndex = bufIndex_;
@synthesize bufSubdiv = bufSubdiv_;
- (IOSDoubleArray *)buf {
  return buf_;
}
- (void)setBuf:(IOSDoubleArray *)buf {
  JreOperatorRetainedAssign(&buf_, self, buf);
}
@synthesize buf = buf_;
@synthesize bufEmpty = bufEmpty_;
- (id<PythagorasDPathIterator>)p {
  return p_;
}
- (void)setP:(id<PythagorasDPathIterator>)p {
  JreOperatorRetainedAssign(&p_, self, p);
}
@synthesize p = p_;
@synthesize flatness_ = flatness__;
@synthesize flatness2 = flatness2_;
@synthesize px = px_;
@synthesize py = py_;
- (IOSDoubleArray *)coords {
  return coords_;
}
- (void)setCoords:(IOSDoubleArray *)coords {
  JreOperatorRetainedAssign(&coords_, self, coords);
}
@synthesize coords = coords_;

- (id)initWithPythagorasDPathIterator:(id<PythagorasDPathIterator>)path
                           withDouble:(double)flatness {
  return [self initPythagorasDFlatteningPathIteratorWithPythagorasDPathIterator:path withDouble:flatness withInt:PythagorasDFlatteningPathIterator_BUFFER_LIMIT];
}

- (id)initPythagorasDFlatteningPathIteratorWithPythagorasDPathIterator:(id<PythagorasDPathIterator>)path
                                                            withDouble:(double)flatness
                                                               withInt:(int)limit {
  if ((self = [super init])) {
    bufEmpty_ = YES;
    JreOperatorRetainedAssign(&coords_, self, [[[IOSDoubleArray alloc] initWithLength:6] autorelease]);
    if (flatness < 0) {
      @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:@"Flatness is less then zero"] autorelease];
    }
    if (limit < 0) {
      @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:@"Limit is less then zero"] autorelease];
    }
    if (path == nil) {
      @throw [[[JavaLangNullPointerException alloc] initWithNSString:@"Path is null"] autorelease];
    }
    self.p = path;
    self.flatness_ = flatness;
    self.flatness2 = flatness * flatness;
    self.bufLimit = limit;
    self.bufSize = [JavaLangMath minWithInt:bufLimit_ withInt:PythagorasDFlatteningPathIterator_BUFFER_SIZE];
    self.buf = [[[IOSDoubleArray alloc] initWithLength:bufSize_] autorelease];
    self.bufIndex = bufSize_;
  }
  return self;
}

- (id)initWithPythagorasDPathIterator:(id<PythagorasDPathIterator>)path
                           withDouble:(double)flatness
                              withInt:(int)limit {
  return [self initPythagorasDFlatteningPathIteratorWithPythagorasDPathIterator:path withDouble:flatness withInt:limit];
}

- (double)flatness {
  return flatness__;
}

- (int)recursionLimit {
  return bufLimit_;
}

- (int)windingRule {
  return [((id<PythagorasDPathIterator>) NIL_CHK(p_)) windingRule];
}

- (BOOL)isDone {
  return bufEmpty_ && [((id<PythagorasDPathIterator>) NIL_CHK(p_)) isDone];
}

- (void)next {
  if (bufEmpty_) {
    [((id<PythagorasDPathIterator>) NIL_CHK(p_)) next];
  }
}

- (int)currentSegmentWithJavaLangDoubleArray:(IOSDoubleArray *)coords {
  if ([self isDone]) {
    @throw [[[JavaUtilNoSuchElementException alloc] initWithNSString:@"Iterator out of bounds"] autorelease];
  }
  [self evaluate];
  int type = bufType_;
  if (type != PythagorasDPathIterator_SEG_CLOSE) {
    [((IOSDoubleArray *) NIL_CHK(coords)) replaceDoubleAtIndex:0 withDouble:px_];
    [((IOSDoubleArray *) NIL_CHK(coords)) replaceDoubleAtIndex:1 withDouble:py_];
    if (type != PythagorasDPathIterator_SEG_MOVETO) {
      type = PythagorasDPathIterator_SEG_LINETO;
    }
  }
  return type;
}

- (void)evaluate {
  if (bufEmpty_) {
    bufType_ = [((id<PythagorasDPathIterator>) NIL_CHK(p_)) currentSegmentWithJavaLangDoubleArray:coords_];
  }
  switch (bufType_) {
    case PythagorasDPathIterator_SEG_MOVETO:
    case PythagorasDPathIterator_SEG_LINETO:
    px_ = [((IOSDoubleArray *) NIL_CHK(coords_)) doubleAtIndex:0];
    py_ = [((IOSDoubleArray *) NIL_CHK(coords_)) doubleAtIndex:1];
    break;
    case PythagorasDPathIterator_SEG_QUADTO:
    if (bufEmpty_) {
      bufIndex_ -= 6;
      [((IOSDoubleArray *) NIL_CHK(buf_)) replaceDoubleAtIndex:bufIndex_ + 0 withDouble:px_];
      [((IOSDoubleArray *) NIL_CHK(buf_)) replaceDoubleAtIndex:bufIndex_ + 1 withDouble:py_];
      [JavaLangSystem arraycopyWithId:coords_ withInt:0 withId:buf_ withInt:bufIndex_ + 2 withInt:4];
      bufSubdiv_ = 0;
    }
    while (bufSubdiv_ < bufLimit_) {
      if ([PythagorasDQuadCurves flatnessSqWithJavaLangDoubleArray:buf_ withInt:bufIndex_] < flatness2_) {
        break;
      }
      if (bufIndex_ <= 4) {
        IOSDoubleArray *tmp = [[[IOSDoubleArray alloc] initWithLength:bufSize_ + PythagorasDFlatteningPathIterator_BUFFER_CAPACITY] autorelease];
        [JavaLangSystem arraycopyWithId:buf_ withInt:bufIndex_ withId:tmp withInt:bufIndex_ + PythagorasDFlatteningPathIterator_BUFFER_CAPACITY withInt:bufSize_ - bufIndex_];
        JreOperatorRetainedAssign(&buf_, self, tmp);
        bufSize_ += PythagorasDFlatteningPathIterator_BUFFER_CAPACITY;
        bufIndex_ += PythagorasDFlatteningPathIterator_BUFFER_CAPACITY;
      }
      [PythagorasDQuadCurves subdivideWithJavaLangDoubleArray:buf_ withInt:bufIndex_ withJavaLangDoubleArray:buf_ withInt:bufIndex_ - 4 withJavaLangDoubleArray:buf_ withInt:bufIndex_];
      bufIndex_ -= 4;
      bufSubdiv_++;
    }
    bufIndex_ += 4;
    px_ = [((IOSDoubleArray *) NIL_CHK(buf_)) doubleAtIndex:bufIndex_];
    py_ = [((IOSDoubleArray *) NIL_CHK(buf_)) doubleAtIndex:bufIndex_ + 1];
    bufEmpty_ = (bufIndex_ == bufSize_ - 2);
    if (bufEmpty_) {
      bufIndex_ = bufSize_;
      bufType_ = PythagorasDPathIterator_SEG_LINETO;
    }
    break;
    case PythagorasDPathIterator_SEG_CUBICTO:
    if (bufEmpty_) {
      bufIndex_ -= 8;
      [((IOSDoubleArray *) NIL_CHK(buf_)) replaceDoubleAtIndex:bufIndex_ + 0 withDouble:px_];
      [((IOSDoubleArray *) NIL_CHK(buf_)) replaceDoubleAtIndex:bufIndex_ + 1 withDouble:py_];
      [JavaLangSystem arraycopyWithId:coords_ withInt:0 withId:buf_ withInt:bufIndex_ + 2 withInt:6];
      bufSubdiv_ = 0;
    }
    while (bufSubdiv_ < bufLimit_) {
      if ([PythagorasDCubicCurves flatnessSqWithJavaLangDoubleArray:buf_ withInt:bufIndex_] < flatness2_) {
        break;
      }
      if (bufIndex_ <= 6) {
        IOSDoubleArray *tmp = [[[IOSDoubleArray alloc] initWithLength:bufSize_ + PythagorasDFlatteningPathIterator_BUFFER_CAPACITY] autorelease];
        [JavaLangSystem arraycopyWithId:buf_ withInt:bufIndex_ withId:tmp withInt:bufIndex_ + PythagorasDFlatteningPathIterator_BUFFER_CAPACITY withInt:bufSize_ - bufIndex_];
        JreOperatorRetainedAssign(&buf_, self, tmp);
        bufSize_ += PythagorasDFlatteningPathIterator_BUFFER_CAPACITY;
        bufIndex_ += PythagorasDFlatteningPathIterator_BUFFER_CAPACITY;
      }
      [PythagorasDCubicCurves subdivideWithJavaLangDoubleArray:buf_ withInt:bufIndex_ withJavaLangDoubleArray:buf_ withInt:bufIndex_ - 6 withJavaLangDoubleArray:buf_ withInt:bufIndex_];
      bufIndex_ -= 6;
      bufSubdiv_++;
    }
    bufIndex_ += 6;
    px_ = [((IOSDoubleArray *) NIL_CHK(buf_)) doubleAtIndex:bufIndex_];
    py_ = [((IOSDoubleArray *) NIL_CHK(buf_)) doubleAtIndex:bufIndex_ + 1];
    bufEmpty_ = (bufIndex_ == bufSize_ - 2);
    if (bufEmpty_) {
      bufIndex_ = bufSize_;
      bufType_ = PythagorasDPathIterator_SEG_LINETO;
    }
    break;
  }
}

- (void)dealloc {
  JreOperatorRetainedAssign(&coords_, self, nil);
  JreOperatorRetainedAssign(&p_, self, nil);
  JreOperatorRetainedAssign(&buf_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  PythagorasDFlatteningPathIterator *typedCopy = (PythagorasDFlatteningPathIterator *) copy;
  typedCopy.bufType = bufType_;
  typedCopy.bufLimit = bufLimit_;
  typedCopy.bufSize = bufSize_;
  typedCopy.bufIndex = bufIndex_;
  typedCopy.bufSubdiv = bufSubdiv_;
  typedCopy.buf = buf_;
  typedCopy.bufEmpty = bufEmpty_;
  typedCopy.p = p_;
  typedCopy.flatness_ = flatness__;
  typedCopy.flatness2 = flatness2_;
  typedCopy.px = px_;
  typedCopy.py = py_;
  typedCopy.coords = coords_;
}

@end
