//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/d/IntersectPoint.java
//
//  Created by Thomas on 7/9/13.
//

#import "JreEmulation.h"

@interface PythagorasDIntersectPoint : NSObject {
 @public
  int begIndex1_;
  int endIndex1_;
  int rule1_;
  int ruleIndex1_;
  double param1_;
  int begIndex2_;
  int endIndex2_;
  int rule2_;
  int ruleIndex2_;
  double x__;
  double y__;
  double param2_;
}

@property (nonatomic, assign) int begIndex1;
@property (nonatomic, assign) int endIndex1;
@property (nonatomic, assign) int rule1;
@property (nonatomic, assign) int ruleIndex1;
@property (nonatomic, assign) double param1;
@property (nonatomic, assign) int begIndex2;
@property (nonatomic, assign) int endIndex2;
@property (nonatomic, assign) int rule2;
@property (nonatomic, assign) int ruleIndex2;
@property (nonatomic, assign) double x_;
@property (nonatomic, assign) double y_;
@property (nonatomic, assign) double param2;

- (id)initWithInt:(int)begIndex1
          withInt:(int)endIndex1
          withInt:(int)begIndex2
          withInt:(int)endIndex2
       withDouble:(double)x
       withDouble:(double)y;
- (id)initWithInt:(int)begIndex1
          withInt:(int)endIndex1
          withInt:(int)rule1
          withInt:(int)ruleIndex1
          withInt:(int)begIndex2
          withInt:(int)endIndex2
          withInt:(int)rule2
          withInt:(int)ruleIndex2
       withDouble:(double)x
       withDouble:(double)y
       withDouble:(double)param1
       withDouble:(double)param2;
- (int)begIndexWithBOOL:(BOOL)isCurrentArea;
- (int)endIndexWithBOOL:(BOOL)isCurrentArea;
- (int)ruleIndexWithBOOL:(BOOL)isCurrentArea;
- (double)paramWithBOOL:(BOOL)isCurrentArea;
- (int)ruleWithBOOL:(BOOL)isCurrentArea;
- (double)x;
- (double)y;
- (void)setBegIndex1WithInt:(int)begIndex;
- (void)setEndIndex1WithInt:(int)endIndex;
- (void)setBegIndex2WithInt:(int)begIndex;
- (void)setEndIndex2WithInt:(int)endIndex;
@end
