//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/d/IRectangle.java
//
//  Created by Thomas on 7/9/13.
//

#import "pythagoras/d/Dimension.h"
#import "pythagoras/d/ILine.h"
#import "pythagoras/d/IPoint.h"
#import "pythagoras/d/Point.h"
#import "pythagoras/d/Rectangle.h"


@implementation PythagorasDIRectangle

+ (int)OUT_LEFT {
  return PythagorasDIRectangle_OUT_LEFT;
}

+ (int)OUT_TOP {
  return PythagorasDIRectangle_OUT_TOP;
}

+ (int)OUT_RIGHT {
  return PythagorasDIRectangle_OUT_RIGHT;
}

+ (int)OUT_BOTTOM {
  return PythagorasDIRectangle_OUT_BOTTOM;
}

- (id)copyWithZoneWithNSZone:(NSZone *)zone OBJC_METHOD_FAMILY_NONE {
  return [[self clone] retain];
}

@end
