//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/d/Point.java
//
//  Created by Thomas on 7/1/13.
//

@protocol PythagorasDIPoint;

#import "JreEmulation.h"
#import "AbstractPoint.h"
#import "java/io/Serializable.h"

@interface PythagorasDPoint : PythagorasDAbstractPoint < JavaIoSerializable > {
 @public
  double x__;
  double y__;
}

@property (nonatomic, assign) double x_;
@property (nonatomic, assign) double y_;

- (id)init;
- (id)initWithDouble:(double)x
          withDouble:(double)y;
- (id)initWithPythagorasDIPoint:(id<PythagorasDIPoint>)p;
- (PythagorasDPoint *)setWithPythagorasDIPoint:(id<PythagorasDIPoint>)p;
- (PythagorasDPoint *)setWithDouble:(double)x
                         withDouble:(double)y;
- (PythagorasDPoint *)multLocalWithDouble:(double)s;
- (PythagorasDPoint *)addLocalWithDouble:(double)dx
                              withDouble:(double)dy;
- (PythagorasDPoint *)rotateLocalWithDouble:(double)angle;
- (PythagorasDPoint *)subtractLocalWithDouble:(double)x
                                   withDouble:(double)y;
- (double)x;
- (double)y;
@end
