//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/util/Callback.java
//
//  Created by Thomas on 7/1/13.
//

@class JavaLangThrowable;

#import "JreEmulation.h"

@protocol PlaynCoreUtilCallback < NSObject >
- (void)onSuccessWithId:(id)result;
- (void)onFailureWithJavaLangThrowable:(JavaLangThrowable *)cause;
@end

@interface PlaynCoreUtilCallback_Chain : NSObject < PlaynCoreUtilCallback > {
 @public
  id<PlaynCoreUtilCallback> onFailure__;
}

@property (nonatomic, retain) id<PlaynCoreUtilCallback> onFailure_;

- (id)initWithPlaynCoreUtilCallback:(id<PlaynCoreUtilCallback>)onFailure;
- (void)onFailureWithJavaLangThrowable:(JavaLangThrowable *)cause;
- (void)onSuccessWithId:(id)param0;
@end
