//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/particle/Generator.java
//
//  Created by Thomas on 7/1/13.
//

@class TPEmitter;

#import "JreEmulation.h"

@interface TPGenerator : NSObject {
}

+ (TPGenerator *)NOOP;
+ (void)setNOOP:(TPGenerator *)NOOP;
+ (TPGenerator *)impulseWithInt:(int)particles;
+ (TPGenerator *)constantWithFloat:(float)particlesPerSecond;
- (BOOL)generateWithTPEmitter:(TPEmitter *)emitter
                    withFloat:(float)now
                    withFloat:(float)dt;
- (id)init;
@end

typedef TPGenerator TripleplayParticleGenerator;

@interface TPGenerator_$1 : TPGenerator {
}

- (BOOL)generateWithTPEmitter:(TPEmitter *)emitter
                    withFloat:(float)now
                    withFloat:(float)dt;
- (id)init;
@end

@interface TPGenerator_$2 : TPGenerator {
 @public
  int val$particles_;
}

@property (nonatomic, assign) int val$particles;

- (BOOL)generateWithTPEmitter:(TPEmitter *)emitter
                    withFloat:(float)now
                    withFloat:(float)dt;
- (id)initWithInt:(int)capture$0;
@end

@interface TPGenerator_$3 : TPGenerator {
 @public
  float _secondsPerParticle_;
  float _accum_;
  float val$particlesPerSecond_;
}

@property (nonatomic, assign) float _secondsPerParticle;
@property (nonatomic, assign) float _accum;
@property (nonatomic, assign) float val$particlesPerSecond;

- (BOOL)generateWithTPEmitter:(TPEmitter *)emitter
                    withFloat:(float)now
                    withFloat:(float)dt;
- (id)initWithFloat:(float)capture$0;
@end
