//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: C:\Users\Thomas\Documents\Eclipse\Tux\tuxblocks\core\src\main\java\tripleplay\particle\TuxParticles.java
//
//  Created by Thomas on 7/1/13.
//

@class TPEmitter;
@class TPParticles_Now;
@class TPTuxEmitter;
@protocol PlaynCoreGroupLayer;
@protocol PlaynCoreImage;

#import "JreEmulation.h"
#import "react/Slot.h"
#import "tripleplay/particle/Particles.h"

@interface TPTuxParticles : TPParticles {
}

- (TPEmitter *)createEmitterWithInt:(int)maxParticles
                 withPlaynCoreImage:(id<PlaynCoreImage>)image
            withPlaynCoreGroupLayer:(id<PlaynCoreGroupLayer>)onLayer;
- (id)init;
@end

typedef TPTuxParticles TripleplayParticleTuxParticles;

@interface TPTuxParticles_$1 : ReactSlot {
 @public
  TPTuxEmitter *val$emitter_;
}

@property (nonatomic, retain) TPTuxEmitter *val$emitter;

- (void)onEmitWithId:(TPParticles_Now *)now;
- (id)initWithTPTuxEmitter:(TPTuxEmitter *)capture$0;
@end
