//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: C:\Users\Thomas\Documents\Eclipse\Tux\tuxblocks\core\src\main\java\tuxkids\tuxblocks\core\HashTest.java
//
//  Created by Thomas on 7/1/13.
//

@class TBHashCode;

#import "JreEmulation.h"
#import "tuxkids/tuxblocks/core/utils/HashCode.h"

@interface TBHashTest : NSObject < TBHashCode_Hashable > {
 @public
  int foo_;
  NSString *bar_;
}

@property (nonatomic, assign) int foo;
@property (nonatomic, copy) NSString *bar;

- (void)addFieldsWithTBHashCode:(TBHashCode *)hashCode;
+ (void)test;
- (id)init;
@end

typedef TBHashTest TuxkidsTuxblocksCoreHashTest;
