//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/anim/Log.java
//
//  Created by Thomas on 7/1/13.
//

@class TripleplayUtilLogger;

#import "JreEmulation.h"

@interface TripleplayAnimLog : NSObject {
}

+ (TripleplayUtilLogger *)log;
- (id)init;
@end
