//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java/tuxkids/tuxblocks/core/defense/walker/FlipWalker.java
//
//  Created by Thomas on 7/10/13.
//

#import "java/lang/Math.h"
#import "pythagoras/f/FloatMath.h"
#import "tuxkids/tuxblocks/core/ImageLayerTintable.h"
#import "tuxkids/tuxblocks/core/defense/Grid.h"
#import "tuxkids/tuxblocks/core/defense/walker/FlipWalker.h"
#import "tuxkids/tuxblocks/core/defense/walker/Walker.h"

@implementation TuxkidsTuxblocksCoreDefenseWalkerFlipWalker

- (id)initWithInt:(int)maxHp
          withInt:(int)walkCellTime {
  return [super initWithInt:maxHp withInt:walkCellTime];
}

- (void)updateMovementWithFloat:(float)perc {
  int dx = -(((PythagorasIPoint *) NIL_CHK(coordinates__)).y_ - ((PythagorasIPoint *) NIL_CHK(lastCoordinates_)).y_);
  int dy = -(((PythagorasIPoint *) NIL_CHK(coordinates__)).x_ - ((PythagorasIPoint *) NIL_CHK(lastCoordinates_)).x_);
  float x = [JavaLangMath maxWithInt:((PythagorasIPoint *) NIL_CHK(coordinates__)).y_ withInt:((PythagorasIPoint *) NIL_CHK(lastCoordinates_)).y_] * [((TuxkidsTuxblocksCoreDefenseGrid *) NIL_CHK(grid_)) cellSize];
  float y = [JavaLangMath maxWithInt:((PythagorasIPoint *) NIL_CHK(coordinates__)).x_ withInt:((PythagorasIPoint *) NIL_CHK(lastCoordinates_)).x_] * [((TuxkidsTuxblocksCoreDefenseGrid *) NIL_CHK(grid_)) cellSize];
  [((TuxkidsTuxblocksCoreImageLayerTintable *) NIL_CHK(layer__)) setTranslationWithFloat:x withFloat:y];
  float scaleX = dx * [PythagorasFFloatMath cosWithFloat:PythagorasFFloatMath_PI * perc];
  if (dx == 0) scaleX = 1;
  float scaleY = dy * [PythagorasFFloatMath cosWithFloat:PythagorasFFloatMath_PI * perc];
  if (dy == 0) scaleY = 1;
  [((TuxkidsTuxblocksCoreImageLayerTintable *) NIL_CHK(layer__)) setScaleWithFloat:scaleX withFloat:scaleY];
}

- (TuxkidsTuxblocksCoreDefenseWalkerWalker *)copy__ OBJC_METHOD_FAMILY_NONE {
  return [[TuxkidsTuxblocksCoreDefenseWalkerFlipWalker alloc] initWithInt:maxHp_ withInt:walkCellTime__];
}

@end
