//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/platform/NativeTextField.java
//
//  Created by Thomas on 7/1/13.
//

@class PlaynCoreKeyboard_TextTypeEnum;
@class ReactSignal;
@class ReactValue;
@class TripleplayPlatformNativeTextField_ModeEnum;
@protocol PlaynCoreFont;
@protocol PythagorasFIRectangle;
@protocol TripleplayPlatformNativeTextField_Transformer;
@protocol TripleplayPlatformNativeTextField_Validator;

#import "JreEmulation.h"
#import "java/lang/Enum.h"

@protocol TripleplayPlatformNativeTextField < NSObject >
- (ReactValue *)text;
- (ReactSignal *)finishedEditing;
- (id<TripleplayPlatformNativeTextField>)setValidatorWithTripleplayPlatformNativeTextField_Validator:(id<TripleplayPlatformNativeTextField_Validator>)validator;
- (id<TripleplayPlatformNativeTextField>)setTransformerWithTripleplayPlatformNativeTextField_Transformer:(id<TripleplayPlatformNativeTextField_Transformer>)transformer;
- (id<TripleplayPlatformNativeTextField>)setTextTypeWithPlaynCoreKeyboard_TextTypeEnum:(PlaynCoreKeyboard_TextTypeEnum *)type;
- (id<TripleplayPlatformNativeTextField>)setFontWithPlaynCoreFont:(id<PlaynCoreFont>)font;
- (id<TripleplayPlatformNativeTextField>)setBoundsWithPythagorasFIRectangle:(id<PythagorasFIRectangle>)bounds;
- (id<TripleplayPlatformNativeTextField>)setAutocapitalizationWithBOOL:(BOOL)useAutocapitalization;
- (id<TripleplayPlatformNativeTextField>)setAutocorrectionWithBOOL:(BOOL)useAutocorrection;
- (id<TripleplayPlatformNativeTextField>)setReturnKeyLabelWithNSString:(NSString *)label;
- (id<TripleplayPlatformNativeTextField>)refreshModeWithTripleplayPlatformNativeTextField_ModeEnum:(TripleplayPlatformNativeTextField_ModeEnum *)mode;
- (void)add;
- (void)remove;
- (void)focus;
- (BOOL)hasFocus;
@end

@protocol TripleplayPlatformNativeTextField_Validator < NSObject >
- (BOOL)isValidWithNSString:(NSString *)text;
@end

@protocol TripleplayPlatformNativeTextField_Transformer < NSObject >
- (NSString *)transformWithNSString:(NSString *)text;
@end

typedef enum {
  TripleplayPlatformNativeTextField_Mode_NORMAL = 0,
  TripleplayPlatformNativeTextField_Mode_SECURE = 1,
  TripleplayPlatformNativeTextField_Mode_MULTI_LINE = 2,
} TripleplayPlatformNativeTextField_Mode;

@interface TripleplayPlatformNativeTextField_ModeEnum : JavaLangEnum < NSCopying > {
}
+ (TripleplayPlatformNativeTextField_ModeEnum *)NORMAL;
+ (TripleplayPlatformNativeTextField_ModeEnum *)SECURE;
+ (TripleplayPlatformNativeTextField_ModeEnum *)MULTI_LINE;
+ (IOSObjectArray *)values;
+ (TripleplayPlatformNativeTextField_ModeEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end
