//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: C:\Users\Thomas\Documents\Eclipse\Tux\tuxblocks\core\src\main\java\tuxkids\tuxblocks\core\defense\walker\Peon.java
//
//  Created by Thomas on 7/1/13.
//

#import "tuxkids/tuxblocks/core/defense/walker/Peon.h"
#import "tuxkids/tuxblocks/core/defense/walker/Walker.h"

@implementation TBPeon

- (id)init {
  return [super initWithInt:10 withInt:500];
}

- (TBWalker *)copy__ OBJC_METHOD_FAMILY_NONE {
  return [[[TBPeon alloc] init] autorelease];
}

- (void)dealloc {
  [super dealloc];
}

@end
