//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/AbstractPlatform.java
//
//  Created by Thomas on 7/1/13.
//

#import "Analytics.h"
#import "Assets.h"
#import "Audio.h"
#import "Callback.h"
#import "Game.h"
#import "Graphics.h"
#import "Json.h"
#import "Keyboard.h"
#import "Log.h"
#import "Mouse.h"
#import "Net.h"
#import "Platform.h"
#import "PlayN.h"
#import "Pointer.h"
#import "RegularExpression.h"
#import "RunQueue.h"
#import "Storage.h"
#import "Touch.h"
#import "UIOverlay.h"
#import "UIOverlayStub.h"
#import "java/lang/Exception.h"
#import "java/lang/Runnable.h"
#import "java/lang/Throwable.h"
#import "java/lang/UnsupportedOperationException.h"

@implementation PlaynCoreAbstractPlatform

- (PlaynCoreUtilRunQueue *)runQueue {
  return runQueue_;
}
- (void)setRunQueue:(PlaynCoreUtilRunQueue *)runQueue {
  JreOperatorRetainedAssign(&runQueue_, self, runQueue);
}
@synthesize runQueue = runQueue_;
- (id<PlaynCoreLog>)log_ {
  return log__;
}
- (void)setLog_:(id<PlaynCoreLog>)log_ {
  JreOperatorRetainedAssign(&log__, self, log_);
}
@synthesize log_ = log__;
- (id<PlaynCorePlayN_LifecycleListener>)lifecycleListener {
  return lifecycleListener_;
}
- (void)setLifecycleListener:(id<PlaynCorePlayN_LifecycleListener>)lifecycleListener {
  JreOperatorRetainedAssign(&lifecycleListener_, self, lifecycleListener);
}
@synthesize lifecycleListener = lifecycleListener_;

- (void)invokeLaterWithJavaLangRunnable:(id<JavaLangRunnable>)runnable {
  [((PlaynCoreUtilRunQueue *) NIL_CHK(runQueue_)) addWithJavaLangRunnable:runnable];
}

- (void)setLifecycleListenerWithPlaynCorePlayN_LifecycleListener:(id<PlaynCorePlayN_LifecycleListener>)listener {
  JreOperatorRetainedAssign(&lifecycleListener_, self, listener);
}

- (id<PlaynCoreLog>)log {
  return log__;
}

- (id<PlaynCoreUIOverlay>)uiOverlay {
  return [[[PlaynCoreUIOverlayStub alloc] init] autorelease];
}

- (void)notifySuccessWithPlaynCoreUtilCallback:(id<PlaynCoreUtilCallback>)callback
                                        withId:(id)result {
  [self invokeLaterWithJavaLangRunnable:[[[PlaynCoreAbstractPlatform_$1 alloc] initWithPlaynCoreUtilCallback:callback withId:result] autorelease]];
}

- (void)notifyFailureWithPlaynCoreUtilCallback:(id<PlaynCoreUtilCallback>)callback
                         withJavaLangThrowable:(JavaLangThrowable *)error {
  [self invokeLaterWithJavaLangRunnable:[[[PlaynCoreAbstractPlatform_$2 alloc] initWithPlaynCoreUtilCallback:callback withJavaLangThrowable:error] autorelease]];
}

- (void)invokeAsyncWithJavaLangRunnable:(id<JavaLangRunnable>)action {
  @throw [[[JavaLangUnsupportedOperationException alloc] init] autorelease];
}

- (id)initWithPlaynCoreLog:(id<PlaynCoreLog>)log {
  if ((self = [super init])) {
    self.log_ = log;
    self.runQueue = [[[PlaynCoreUtilRunQueue alloc] initWithPlaynCoreLog:log] autorelease];
  }
  return self;
}

- (void)onPause {
  if (lifecycleListener_ != nil) {
    @try {
      [lifecycleListener_ onPause];
    }
    @catch (JavaLangException *e) {
      [((id<PlaynCoreLog>) NIL_CHK(log__)) warnWithNSString:@"LifecycleListener.onPause failure" withJavaLangThrowable:e];
    }
  }
}

- (void)onResume {
  if (lifecycleListener_ != nil) {
    @try {
      [lifecycleListener_ onResume];
    }
    @catch (JavaLangException *e) {
      [((id<PlaynCoreLog>) NIL_CHK(log__)) warnWithNSString:@"LifecycleListener.onResume failure" withJavaLangThrowable:e];
    }
  }
}

- (void)onExit {
  if (lifecycleListener_ != nil) {
    @try {
      [lifecycleListener_ onExit];
    }
    @catch (JavaLangException *e) {
      [((id<PlaynCoreLog>) NIL_CHK(log__)) warnWithNSString:@"LifecycleListener.onExit failure" withJavaLangThrowable:e];
    }
  }
}

- (id<PlaynCoreAnalytics>)analytics {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<PlaynCoreAssets>)assets {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<PlaynCoreAudio>)audio {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<PlaynCoreGraphics>)graphics {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<PlaynCoreJson>)json {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<PlaynCoreKeyboard>)keyboard {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<PlaynCoreMouse>)mouse {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<PlaynCoreNet>)net {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (void)openURLWithNSString:(NSString *)param0 {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (id<PlaynCorePointer>)pointer {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (float)random {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<PlaynCoreRegularExpression>)regularExpression {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (void)runWithPlaynCoreGame:(id<PlaynCoreGame>)param0 {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (void)setPropagateEventsWithBOOL:(BOOL)param0 {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (id<PlaynCoreStorage>)storage {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (int)tick {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (double)time {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<PlaynCoreTouch>)touch {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (PlaynCorePlatform_TypeEnum *)type {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&lifecycleListener_, self, nil);
  JreOperatorRetainedAssign(&log__, self, nil);
  JreOperatorRetainedAssign(&runQueue_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  PlaynCoreAbstractPlatform *typedCopy = (PlaynCoreAbstractPlatform *) copy;
  typedCopy.runQueue = runQueue_;
  typedCopy.log_ = log__;
  typedCopy.lifecycleListener = lifecycleListener_;
}

@end
@implementation PlaynCoreAbstractPlatform_$1

- (id<PlaynCoreUtilCallback>)val$callback {
  return val$callback_;
}
- (void)setVal$callback:(id<PlaynCoreUtilCallback>)val$callback {
  JreOperatorRetainedAssign(&val$callback_, self, val$callback);
}
@synthesize val$callback = val$callback_;
- (id)val$result {
  return val$result_;
}
- (void)setVal$result:(id)val$result {
  JreOperatorRetainedAssign(&val$result_, self, val$result);
}
@synthesize val$result = val$result_;

- (void)run {
  [((id<PlaynCoreUtilCallback>) NIL_CHK(val$callback_)) onSuccessWithId:val$result_];
}

- (id)initWithPlaynCoreUtilCallback:(id<PlaynCoreUtilCallback>)capture$0
                             withId:(id)capture$1 {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&val$callback_, self, capture$0);
    JreOperatorRetainedAssign(&val$result_, self, capture$1);
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&val$result_, self, nil);
  JreOperatorRetainedAssign(&val$callback_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  PlaynCoreAbstractPlatform_$1 *typedCopy = (PlaynCoreAbstractPlatform_$1 *) copy;
  typedCopy.val$callback = val$callback_;
  typedCopy.val$result = val$result_;
}

@end
@implementation PlaynCoreAbstractPlatform_$2

- (id<PlaynCoreUtilCallback>)val$callback {
  return val$callback_;
}
- (void)setVal$callback:(id<PlaynCoreUtilCallback>)val$callback {
  JreOperatorRetainedAssign(&val$callback_, self, val$callback);
}
@synthesize val$callback = val$callback_;
- (JavaLangThrowable *)val$error {
  return val$error_;
}
- (void)setVal$error:(JavaLangThrowable *)val$error {
  JreOperatorRetainedAssign(&val$error_, self, val$error);
}
@synthesize val$error = val$error_;

- (void)run {
  [((id<PlaynCoreUtilCallback>) NIL_CHK(val$callback_)) onFailureWithJavaLangThrowable:val$error_];
}

- (id)initWithPlaynCoreUtilCallback:(id<PlaynCoreUtilCallback>)capture$0
              withJavaLangThrowable:(JavaLangThrowable *)capture$1 {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&val$callback_, self, capture$0);
    JreOperatorRetainedAssign(&val$error_, self, capture$1);
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&val$error_, self, nil);
  JreOperatorRetainedAssign(&val$callback_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  PlaynCoreAbstractPlatform_$2 *typedCopy = (PlaynCoreAbstractPlatform_$2 *) copy;
  typedCopy.val$callback = val$callback_;
  typedCopy.val$error = val$error_;
}

@end
