//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/BatchImpl.java
//
//  Created by Thomas on 7/1/13.
//

@protocol JavaUtilMap;
@protocol PlaynCoreStorage;

#import "JreEmulation.h"
#import "Storage.h"

@interface PlaynCoreBatchImpl : NSObject < PlaynCoreStorage_Batch > {
 @public
  id<PlaynCoreStorage> storage_;
  id<JavaUtilMap> updates_;
}

@property (nonatomic, retain) id<PlaynCoreStorage> storage;
@property (nonatomic, retain) id<JavaUtilMap> updates;

- (id)initWithPlaynCoreStorage:(id<PlaynCoreStorage>)storage;
- (void)setItemWithNSString:(NSString *)key
               withNSString:(NSString *)data;
- (void)removeItemWithNSString:(NSString *)key;
- (void)commit;
- (void)onBeforeCommit;
- (void)setImplWithNSString:(NSString *)key
               withNSString:(NSString *)data;
- (void)removeImplWithNSString:(NSString *)key;
- (void)onAfterCommit;
@end
