//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/Connection.java
//
//  Created by Thomas on 7/1/13.
//

#import "JreEmulation.h"

@protocol PlaynCoreConnection < NSObject >
- (void)disconnect;
@end
