//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/gl/QuadShader.java
//
//  Created by Thomas on 7/1/13.
//

@class PlaynCoreGlGLContext;
@protocol PlaynCoreGlGLBuffer_Float;
@protocol PlaynCoreGlGLBuffer_Short;
@protocol PlaynCoreGlGLShader_Attrib;
@protocol PlaynCoreGlGLShader_Uniform2f;
@protocol PlaynCoreGlGLShader_Uniform4fv;

#import "JreEmulation.h"
#import "playn/core/gl/GLShader.h"

#define PlaynCoreGlQuadShader_BASE_VEC4S_PER_QUAD 3
#define PlaynCoreGlQuadShader_ELEMENTS_PER_QUAD 6
#define PlaynCoreGlQuadShader_VERTEX_SIZE 3
#define PlaynCoreGlQuadShader_VERTICES_PER_QUAD 4

@interface PlaynCoreGlQuadShader : PlaynCoreGlGLShader {
 @public
  int maxQuads_;
}

@property (nonatomic, assign) int maxQuads;

+ (NSString *)VERT_UNIFS;
+ (NSString *)VERT_ATTRS;
+ (NSString *)VERT_VARS;
+ (NSString *)VERT_EXTRACTDATA;
+ (NSString *)VERT_SETPOS;
+ (NSString *)VERT_SETTEX;
+ (NSString *)VERT_SETCOLOR;
+ (NSString *)VERTEX_SHADER;
+ (BOOL)isLikelyToPerformWithPlaynCoreGlGLContext:(PlaynCoreGlGLContext *)ctx;
+ (int)usableMaxUniformVectorsWithPlaynCoreGlGLContext:(PlaynCoreGlGLContext *)ctx;
- (id)initWithPlaynCoreGlGLContext:(PlaynCoreGlGLContext *)ctx;
- (NSString *)description;
- (int)vec4sPerQuad;
- (int)extraVec4s;
- (NSString *)vertexShader;
- (NSString *)baseVertexShader;
- (PlaynCoreGlGLShader_Core *)createTextureCore;
- (PlaynCoreGlGLShader_Core *)createColorCore;
@end

@interface PlaynCoreGlQuadShader_QuadCore : PlaynCoreGlGLShader_Core {
 @public
  PlaynCoreGlQuadShader *this$1_;
  id<PlaynCoreGlGLShader_Uniform2f> uScreenSize_;
  id<PlaynCoreGlGLShader_Uniform4fv> uData_;
  id<PlaynCoreGlGLShader_Attrib> aVertex_;
  id<PlaynCoreGlGLBuffer_Float> data_;
  id<PlaynCoreGlGLBuffer_Short> vertices_, elements_;
  int quadCounter_;
  float arTint_, gbTint_;
}

@property (nonatomic, retain) PlaynCoreGlQuadShader *this$1;
@property (nonatomic, retain) id<PlaynCoreGlGLShader_Uniform2f> uScreenSize;
@property (nonatomic, retain) id<PlaynCoreGlGLShader_Uniform4fv> uData;
@property (nonatomic, retain) id<PlaynCoreGlGLShader_Attrib> aVertex;
@property (nonatomic, retain) id<PlaynCoreGlGLBuffer_Float> data;
@property (nonatomic, retain) id<PlaynCoreGlGLBuffer_Short> vertices;
@property (nonatomic, retain) id<PlaynCoreGlGLBuffer_Short> elements;
@property (nonatomic, assign) int quadCounter;
@property (nonatomic, assign) float arTint;
@property (nonatomic, assign) float gbTint;

- (id)initWithPlaynCoreGlQuadShader:(PlaynCoreGlQuadShader *)outer$
                       withNSString:(NSString *)vertShader
                       withNSString:(NSString *)fragShader;
- (void)activateWithInt:(int)fbufWidth
                withInt:(int)fbufHeight;
- (void)prepareWithInt:(int)tint
              withBOOL:(BOOL)justActivated;
- (void)flush;
- (void)destroy;
- (void)addQuadWithFloat:(float)m00
               withFloat:(float)m01
               withFloat:(float)m10
               withFloat:(float)m11
               withFloat:(float)tx
               withFloat:(float)ty
               withFloat:(float)x1
               withFloat:(float)y1
               withFloat:(float)sx1
               withFloat:(float)sy1
               withFloat:(float)x2
               withFloat:(float)y2
               withFloat:(float)sx2
               withFloat:(float)sy2
               withFloat:(float)x3
               withFloat:(float)y3
               withFloat:(float)sx3
               withFloat:(float)sy3
               withFloat:(float)x4
               withFloat:(float)y4
               withFloat:(float)sx4
               withFloat:(float)sy4;
- (void)addExtraDataWithPlaynCoreGlGLBuffer_Float:(id<PlaynCoreGlGLBuffer_Float>)data;
@end
