//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/ui/CheckBox.java
//
//  Created by Thomas on 7/1/13.
//

#import "Connection.h"
#import "Element.h"
#import "IOSClass.h"
#import "Icon.h"
#import "Icons.h"
#import "Image.h"
#import "ImageLayer.h"
#import "Layer.h"
#import "Pointer.h"
#import "Sound.h"
#import "Style.h"
#import "Value.h"
#import "Widget.h"
#import "java/lang/Boolean.h"

@implementation TripleplayUiCheckBox

- (ReactValue *)checked {
  return checked_;
}
- (void)setChecked:(ReactValue *)checked {
  JreOperatorRetainedAssign(&checked_, self, checked);
}
@synthesize checked = checked_;
- (NSString *)_checkStr {
  return _checkStr_;
}
- (void)set_checkStr:(NSString *)_checkStr {
  JreOperatorRetainedAssign(&_checkStr_, self, _checkStr);
}
@synthesize _checkStr = _checkStr_;
- (id<TripleplayUiIcon>)_checkIcon {
  return _checkIcon_;
}
- (void)set_checkIcon:(id<TripleplayUiIcon>)_checkIcon {
  JreOperatorRetainedAssign(&_checkIcon_, self, _checkIcon);
}
@synthesize _checkIcon = _checkIcon_;
- (id<PlaynCoreSound>)_actionSound {
  return _actionSound_;
}
- (void)set_actionSound:(id<PlaynCoreSound>)_actionSound {
  JreOperatorRetainedAssign(&_actionSound_, self, _actionSound);
}
@synthesize _actionSound = _actionSound_;

- (id)init {
  return [self initTripleplayUiCheckBoxWithUnichar:0x2713];
}

- (id)initTripleplayUiCheckBoxWithUnichar:(unichar)checkChar {
  return [self initTripleplayUiCheckBoxWithUnichar:checkChar withTripleplayUiIcon:(id<TripleplayUiIcon>) nil];
}

- (id)initWithUnichar:(unichar)checkChar {
  return [self initTripleplayUiCheckBoxWithUnichar:checkChar];
}

- (id)initWithTripleplayUiIcon:(id<TripleplayUiIcon>)checkIcon {
  return [self initTripleplayUiCheckBoxWithUnichar:(unichar) 0 withTripleplayUiIcon:checkIcon];
}

- (id)initWithPlaynCoreImage:(id<PlaynCoreImage>)checkIcon {
  return [self initTripleplayUiCheckBoxWithUnichar:(unichar) 0 withTripleplayUiIcon:[TripleplayUiIcons imageWithPlaynCoreImage:checkIcon]];
}

- (id)initTripleplayUiCheckBoxWithUnichar:(unichar)checkChar
                     withTripleplayUiIcon:(id<TripleplayUiIcon>)checkIcon {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&checked_, self, ((ReactValue *) [ReactValue createWithId:[JavaLangBoolean valueOfWithBOOL:NO]]));
    JreOperatorRetainedAssign(&_checkStr_, self, [NSString valueOfChar:checkChar]);
    JreOperatorRetainedAssign(&_checkIcon_, self, checkIcon);
    (void) [((ReactValue *) NIL_CHK(checked_)) connectWithReactValueView_Listener:[[[TripleplayUiCheckBox_$1 alloc] initWithTripleplayUiCheckBox:self] autorelease]];
  }
  return self;
}

- (id)initWithUnichar:(unichar)checkChar
 withTripleplayUiIcon:(id<TripleplayUiIcon>)checkIcon {
  return [self initTripleplayUiCheckBoxWithUnichar:checkChar withTripleplayUiIcon:checkIcon];
}

- (IOSClass *)getStyleClass {
  return [IOSClass classWithClass:[TripleplayUiCheckBox class]];
}

- (NSString *)text {
  return (_checkIcon_ == nil) ? _checkStr_ : nil;
}

- (id<TripleplayUiIcon>)icon {
  return _checkIcon_;
}

- (void)onClickWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event {
  if (_actionSound_ != nil) [_actionSound_ play];
  (void) [((ReactValue *) NIL_CHK(checked_)) updateWithId:[JavaLangBoolean valueOfWithBOOL:![((JavaLangBoolean *) [((ReactValue *) NIL_CHK(checked_)) get]) booleanValue]]];
}

- (void)layout {
  [super layout];
  JreOperatorRetainedAssign(&_actionSound_, self, ((id<PlaynCoreSound>) [self resolveStyleWithTripleplayUiStyle:[TripleplayUiStyle ACTION_SOUND]]));
  [self updateCheckViz];
}

- (void)updateCheckViz {
  BOOL isChecked = [((JavaLangBoolean *) [((ReactValue *) NIL_CHK(checked_)) get]) booleanValue];
  if ([((TripleplayUiWidget_Glyph *) NIL_CHK(_tglyph_)) layer] != nil) (void) [((id<PlaynCoreImageLayer>) [((TripleplayUiWidget_Glyph *) NIL_CHK(_tglyph_)) layer]) setVisibleWithBOOL:isChecked];
  if (_ilayer_ != nil) (void) [_ilayer_ setVisibleWithBOOL:isChecked];
}

- (void)dealloc {
  JreOperatorRetainedAssign(&_actionSound_, self, nil);
  JreOperatorRetainedAssign(&_checkIcon_, self, nil);
  JreOperatorRetainedAssign(&_checkStr_, self, nil);
  JreOperatorRetainedAssign(&checked_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TripleplayUiCheckBox *typedCopy = (TripleplayUiCheckBox *) copy;
  typedCopy.checked = checked_;
  typedCopy._checkStr = _checkStr_;
  typedCopy._checkIcon = _checkIcon_;
  typedCopy._actionSound = _actionSound_;
}

@end
@implementation TripleplayUiCheckBox_$1

- (TripleplayUiCheckBox *)this$0 {
  return this$0_;
}
- (void)setThis$0:(TripleplayUiCheckBox *)this$0 {
  JreOperatorRetainedAssign(&this$0_, self, this$0);
}
@synthesize this$0 = this$0_;

- (void)onEmitWithId:(JavaLangBoolean *)checked {
  [this$0_ updateCheckViz];
}

- (id)initWithTripleplayUiCheckBox:(TripleplayUiCheckBox *)outer$ {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&this$0_, self, outer$);
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&this$0_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TripleplayUiCheckBox_$1 *typedCopy = (TripleplayUiCheckBox_$1 *) copy;
  typedCopy.this$0 = this$0_;
}

@end
