//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/ui/TextWidget.java
//
//  Created by Thomas on 7/1/13.
//

@class JavaLangThrowable;
@class PythagorasFDimension;
@class ReactUnitSlot;
@class TripleplayUiStyle_HAlignEnum;
@class TripleplayUiStyle_PosEnum;
@class TripleplayUiStyle_VAlignEnum;
@class TripleplayUiWidget_Glyph;
@class TripleplayUtilEffectRenderer;
@protocol PlaynCoreLayer;
@protocol PlaynCoreTextLayout;
@protocol TripleplayUiIcon;

#import "JreEmulation.h"
#import "Callback.h"
#import "Element.h"
#import "Slot.h"
#import "Widget.h"

@interface TripleplayUiTextWidget : TripleplayUiWidget {
 @public
  TripleplayUiWidget_Glyph *_tglyph_;
  id<PlaynCoreLayer> _ilayer_;
}

@property (nonatomic, retain) TripleplayUiWidget_Glyph *_tglyph;
@property (nonatomic, retain) id<PlaynCoreLayer> _ilayer;

- (NSString *)text;
- (id<TripleplayUiIcon>)icon;
- (ReactUnitSlot *)textDidChange;
- (ReactSlot *)iconDidChange;
- (void)wasRemoved;
- (TripleplayUiElement_LayoutData *)createLayoutDataWithFloat:(float)hintX
                                                    withFloat:(float)hintY;
- (id)init;
@end

@interface TripleplayUiTextWidget_TextLayoutData : TripleplayUiElement_LayoutData {
 @public
  TripleplayUiTextWidget *this$2_;
  TripleplayUiStyle_HAlignEnum *halign_;
  TripleplayUiStyle_VAlignEnum *valign_;
  TripleplayUiStyle_PosEnum *iconPos_;
  int iconGap_;
  BOOL iconCuddle_;
  int color_;
  BOOL underlined_;
  BOOL wrap_;
  id<PlaynCoreTextLayout> text_;
  TripleplayUtilEffectRenderer *renderer_;
}

@property (nonatomic, retain) TripleplayUiTextWidget *this$2;
@property (nonatomic, retain) TripleplayUiStyle_HAlignEnum *halign;
@property (nonatomic, retain) TripleplayUiStyle_VAlignEnum *valign;
@property (nonatomic, retain) TripleplayUiStyle_PosEnum *iconPos;
@property (nonatomic, assign) int iconGap;
@property (nonatomic, assign) BOOL iconCuddle;
@property (nonatomic, assign) int color;
@property (nonatomic, assign) BOOL underlined;
@property (nonatomic, assign) BOOL wrap;
@property (nonatomic, retain) id<PlaynCoreTextLayout> text;
@property (nonatomic, retain) TripleplayUtilEffectRenderer *renderer;

- (id)initWithTripleplayUiTextWidget:(TripleplayUiTextWidget *)outer$
                           withFloat:(float)hintX
                           withFloat:(float)hintY;
- (PythagorasFDimension *)computeSizeWithFloat:(float)hintX
                                     withFloat:(float)hintY;
- (void)layoutWithFloat:(float)left
              withFloat:(float)top
              withFloat:(float)width
              withFloat:(float)height;
- (void)accommodateIconWithPythagorasFDimension:(PythagorasFDimension *)hints
                                       withBOOL:(BOOL)haveText;
- (void)addTextSizeWithPythagorasFDimension:(PythagorasFDimension *)size;
- (void)updateTextGlyphWithFloat:(float)tx
                       withFloat:(float)ty
                       withFloat:(float)availWidth
                       withFloat:(float)availHeight;
- (float)textWidth;
- (float)textHeight;
@end

@interface TripleplayUiTextWidget_$1 : ReactSlot {
 @public
  TripleplayUiTextWidget *this$0_;
}

@property (nonatomic, retain) TripleplayUiTextWidget *this$0;

- (void)onEmitWithId:(id<TripleplayUiIcon>)icon;
- (id)initWithTripleplayUiTextWidget:(TripleplayUiTextWidget *)outer$;
@end

@interface TripleplayUiTextWidget_$1_$1 : NSObject < PlaynCoreUtilCallback > {
 @public
  TripleplayUiTextWidget_$1 *this$0_;
}

@property (nonatomic, retain) TripleplayUiTextWidget_$1 *this$0;

- (void)onSuccessWithId:(id<TripleplayUiIcon>)resource;
- (void)onFailureWithJavaLangThrowable:(JavaLangThrowable *)err;
- (id)initWithTripleplayUiTextWidget_$1:(TripleplayUiTextWidget_$1 *)outer$;
@end
