//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/ui/Widget.java
//
//  Created by Thomas on 7/1/13.
//

#import "Connection.h"
#import "Element.h"
#import "Glyph.h"
#import "GroupLayer.h"
#import "Pointer.h"

@implementation TripleplayUiWidget

- (void)enableInteraction {
  [self setWithTripleplayUiElement_FlagEnum:[TripleplayUiElement_FlagEnum HIT_DESCEND] withBOOL:NO];
  [self setWithTripleplayUiElement_FlagEnum:[TripleplayUiElement_FlagEnum HIT_ABSORB] withBOOL:YES];
  (void) [((id<PlaynCoreGroupLayer>) NIL_CHK(layer_)) addListenerWithPlaynCorePointer_Listener:[[[TripleplayUiWidget_$1 alloc] initWithTripleplayUiWidget:self] autorelease]];
}

- (void)onPointerStartWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event
                                       withFloat:(float)x
                                       withFloat:(float)y {
}

- (void)onPointerDragWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event
                                      withFloat:(float)x
                                      withFloat:(float)y {
}

- (void)onPointerEndWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event
                                     withFloat:(float)x
                                     withFloat:(float)y {
}

- (void)onPointerCancelWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event {
}

- (id)init {
  return [super init];
}

- (void)dealloc {
  [super dealloc];
}

@end
@implementation TripleplayUiWidget_Glyph

- (id)initWithTripleplayUiWidget:(TripleplayUiWidget *)outer$ {
  return [super initWithPlaynCoreGroupLayer:outer$.layer];
}

- (void)dealloc {
  [super dealloc];
}

@end
@implementation TripleplayUiWidget_$1

- (TripleplayUiWidget *)this$0 {
  return this$0_;
}
- (void)setThis$0:(TripleplayUiWidget *)this$0 {
  JreOperatorRetainedAssign(&this$0_, self, this$0);
}
@synthesize this$0 = this$0_;

- (void)onPointerStartWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event {
  [this$0_ onPointerStartWithPlaynCorePointer_Event:event withFloat:[((id<PlaynCorePointer_Event>) NIL_CHK(event)) localX] withFloat:[((id<PlaynCorePointer_Event>) NIL_CHK(event)) localY]];
}

- (void)onPointerDragWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event {
  [this$0_ onPointerDragWithPlaynCorePointer_Event:event withFloat:[((id<PlaynCorePointer_Event>) NIL_CHK(event)) localX] withFloat:[((id<PlaynCorePointer_Event>) NIL_CHK(event)) localY]];
}

- (void)onPointerEndWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event {
  [this$0_ onPointerEndWithPlaynCorePointer_Event:event withFloat:[((id<PlaynCorePointer_Event>) NIL_CHK(event)) localX] withFloat:[((id<PlaynCorePointer_Event>) NIL_CHK(event)) localY]];
}

- (void)onPointerCancelWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event {
  [this$0_ onPointerCancelWithPlaynCorePointer_Event:event];
}

- (id)initWithTripleplayUiWidget:(TripleplayUiWidget *)outer$ {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&this$0_, self, outer$);
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&this$0_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TripleplayUiWidget_$1 *typedCopy = (TripleplayUiWidget_$1 *) copy;
  typedCopy.this$0 = this$0_;
}

@end
