//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/d/CubicCurve.java
//
//  Created by Thomas on 7/1/13.
//

@class IOSDoubleArray;
@class IOSObjectArray;
@protocol PythagorasDICubicCurve;
@protocol PythagorasDIPoint;

#import "JreEmulation.h"
#import "java/io/Serializable.h"
#import "pythagoras/d/AbstractCubicCurve.h"

@interface PythagorasDCubicCurve : PythagorasDAbstractCubicCurve < JavaIoSerializable > {
 @public
  double x1__;
  double y1__;
  double ctrlx1_;
  double ctrly1_;
  double ctrlx2_;
  double ctrly2_;
  double x2__;
  double y2__;
}

@property (nonatomic, assign) double x1_;
@property (nonatomic, assign) double y1_;
@property (nonatomic, assign) double ctrlx1;
@property (nonatomic, assign) double ctrly1;
@property (nonatomic, assign) double ctrlx2;
@property (nonatomic, assign) double ctrly2;
@property (nonatomic, assign) double x2_;
@property (nonatomic, assign) double y2_;

- (id)init;
- (id)initWithDouble:(double)x1
          withDouble:(double)y1
          withDouble:(double)ctrlx1
          withDouble:(double)ctrly1
          withDouble:(double)ctrlx2
          withDouble:(double)ctrly2
          withDouble:(double)x2
          withDouble:(double)y2;
- (void)setCurveWithDouble:(double)x1
                withDouble:(double)y1
                withDouble:(double)ctrlx1
                withDouble:(double)ctrly1
                withDouble:(double)ctrlx2
                withDouble:(double)ctrly2
                withDouble:(double)x2
                withDouble:(double)y2;
- (void)setCurveWithPythagorasDIPoint:(id<PythagorasDIPoint>)p1
                withPythagorasDIPoint:(id<PythagorasDIPoint>)cp1
                withPythagorasDIPoint:(id<PythagorasDIPoint>)cp2
                withPythagorasDIPoint:(id<PythagorasDIPoint>)p2;
- (void)setCurveWithJavaLangDoubleArray:(IOSDoubleArray *)coords
                                withInt:(int)offset;
- (void)setCurveWithPythagorasDIPointArray:(IOSObjectArray *)points
                                   withInt:(int)offset;
- (void)setCurveWithPythagorasDICubicCurve:(id<PythagorasDICubicCurve>)curve;
- (double)x1;
- (double)y1;
- (double)ctrlX1;
- (double)ctrlY1;
- (double)ctrlX2;
- (double)ctrlY2;
- (double)x2;
- (double)y2;
@end
