//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/d/IVector3.java
//
//  Created by Thomas on 7/1/13.
//

@class IOSDoubleArray;
@class JavaNioDoubleBuffer;
@class PythagorasDVector3;

#import "JreEmulation.h"

@protocol PythagorasDIVector3 < NSObject >
- (double)x;
- (double)y;
- (double)z;
- (double)dotWithPythagorasDIVector3:(id<PythagorasDIVector3>)other;
- (PythagorasDVector3 *)crossWithPythagorasDIVector3:(id<PythagorasDIVector3>)other;
- (PythagorasDVector3 *)crossWithPythagorasDIVector3:(id<PythagorasDIVector3>)other
                              withPythagorasDVector3:(PythagorasDVector3 *)result;
- (double)tripleWithPythagorasDIVector3:(id<PythagorasDIVector3>)b
                withPythagorasDIVector3:(id<PythagorasDIVector3>)c;
- (PythagorasDVector3 *)negate;
- (PythagorasDVector3 *)negateWithPythagorasDVector3:(PythagorasDVector3 *)result;
- (PythagorasDVector3 *)abs;
- (PythagorasDVector3 *)absWithPythagorasDVector3:(PythagorasDVector3 *)result;
- (PythagorasDVector3 *)normalize;
- (PythagorasDVector3 *)normalizeWithPythagorasDVector3:(PythagorasDVector3 *)result;
- (double)angleWithPythagorasDIVector3:(id<PythagorasDIVector3>)other;
- (double)length;
- (double)lengthSquared;
- (double)distanceWithPythagorasDIVector3:(id<PythagorasDIVector3>)other;
- (double)distanceSquaredWithPythagorasDIVector3:(id<PythagorasDIVector3>)other;
- (double)manhattanDistanceWithPythagorasDIVector3:(id<PythagorasDIVector3>)other;
- (PythagorasDVector3 *)multWithDouble:(double)v;
- (PythagorasDVector3 *)multWithDouble:(double)v
                withPythagorasDVector3:(PythagorasDVector3 *)result;
- (PythagorasDVector3 *)multWithPythagorasDIVector3:(id<PythagorasDIVector3>)other;
- (PythagorasDVector3 *)multWithPythagorasDIVector3:(id<PythagorasDIVector3>)other
                             withPythagorasDVector3:(PythagorasDVector3 *)result;
- (PythagorasDVector3 *)addWithPythagorasDIVector3:(id<PythagorasDIVector3>)other;
- (PythagorasDVector3 *)addWithPythagorasDIVector3:(id<PythagorasDIVector3>)other
                            withPythagorasDVector3:(PythagorasDVector3 *)result;
- (PythagorasDVector3 *)subtractWithPythagorasDIVector3:(id<PythagorasDIVector3>)other;
- (PythagorasDVector3 *)subtractWithPythagorasDIVector3:(id<PythagorasDIVector3>)other
                                 withPythagorasDVector3:(PythagorasDVector3 *)result;
- (PythagorasDVector3 *)addWithDouble:(double)x
                           withDouble:(double)y
                           withDouble:(double)z;
- (PythagorasDVector3 *)addWithDouble:(double)x
                           withDouble:(double)y
                           withDouble:(double)z
               withPythagorasDVector3:(PythagorasDVector3 *)result;
- (PythagorasDVector3 *)addScaledWithPythagorasDIVector3:(id<PythagorasDIVector3>)other
                                              withDouble:(double)v;
- (PythagorasDVector3 *)addScaledWithPythagorasDIVector3:(id<PythagorasDIVector3>)other
                                              withDouble:(double)v
                                  withPythagorasDVector3:(PythagorasDVector3 *)result;
- (PythagorasDVector3 *)lerpWithPythagorasDIVector3:(id<PythagorasDIVector3>)other
                                         withDouble:(double)t;
- (PythagorasDVector3 *)lerpWithPythagorasDIVector3:(id<PythagorasDIVector3>)other
                                         withDouble:(double)t
                             withPythagorasDVector3:(PythagorasDVector3 *)result;
- (double)getWithInt:(int)idx;
- (void)getWithJavaLangDoubleArray:(IOSDoubleArray *)values;
- (JavaNioDoubleBuffer *)getWithJavaNioDoubleBuffer:(JavaNioDoubleBuffer *)buf;
@end
