//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: playn/core/gl/AbstractSurfaceGL.java
//
//  Created by Thomas on 7/1/13.
//

@class IOSFloatArray;
@class IOSIntArray;
@class PlaynCoreGlAbstractImageGL;
@class PlaynCoreGlGLContext;
@class PlaynCoreGlGLShader;
@protocol JavaUtilList;
@protocol PlaynCoreImage;
@protocol PlaynCoreInternalTransform;
@protocol PlaynCoreLayer;
@protocol PlaynCorePattern;

#import "JreEmulation.h"
#import "Surface.h"

@interface PlaynCoreGlAbstractSurfaceGL : NSObject < PlaynCoreSurface > {
 @public
  PlaynCoreGlGLContext *ctx_;
  id<JavaUtilList> transformStack_;
  int fillColor_;
  int tint_;
  PlaynCoreGlAbstractImageGL *fillPattern_;
  PlaynCoreGlGLShader *shader_;
}

@property (nonatomic, retain) PlaynCoreGlGLContext *ctx;
@property (nonatomic, retain) id<JavaUtilList> transformStack;
@property (nonatomic, assign) int fillColor;
@property (nonatomic, assign) int tint;
@property (nonatomic, retain) PlaynCoreGlAbstractImageGL *fillPattern;
@property (nonatomic, retain) PlaynCoreGlGLShader *shader;

- (id)initWithPlaynCoreGlGLContext:(PlaynCoreGlGLContext *)ctx;
- (void)bindFramebuffer;
- (id<PlaynCoreSurface>)clear;
- (id<PlaynCoreSurface>)drawImageWithPlaynCoreImage:(id<PlaynCoreImage>)image
                                          withFloat:(float)x
                                          withFloat:(float)y;
- (id<PlaynCoreSurface>)drawImageWithPlaynCoreImage:(id<PlaynCoreImage>)image
                                          withFloat:(float)x
                                          withFloat:(float)y
                                          withFloat:(float)dw
                                          withFloat:(float)dh;
- (id<PlaynCoreSurface>)drawImageWithPlaynCoreImage:(id<PlaynCoreImage>)image
                                          withFloat:(float)dx
                                          withFloat:(float)dy
                                          withFloat:(float)dw
                                          withFloat:(float)dh
                                          withFloat:(float)sx
                                          withFloat:(float)sy
                                          withFloat:(float)sw
                                          withFloat:(float)sh;
- (id<PlaynCoreSurface>)drawImageCenteredWithPlaynCoreImage:(id<PlaynCoreImage>)img
                                                  withFloat:(float)x
                                                  withFloat:(float)y;
- (id<PlaynCoreSurface>)drawLayerWithPlaynCoreLayer:(id<PlaynCoreLayer>)layer;
- (id<PlaynCoreSurface>)drawLineWithFloat:(float)x0
                                withFloat:(float)y0
                                withFloat:(float)x1
                                withFloat:(float)y1
                                withFloat:(float)width;
- (id<PlaynCoreSurface>)fillRectWithFloat:(float)x
                                withFloat:(float)y
                                withFloat:(float)width
                                withFloat:(float)height;
- (id<PlaynCoreSurface>)fillTrianglesWithJavaLangFloatArray:(IOSFloatArray *)xys
                                   withJavaLangIntegerArray:(IOSIntArray *)indices;
- (id<PlaynCoreSurface>)fillTrianglesWithJavaLangFloatArray:(IOSFloatArray *)xys
                                     withJavaLangFloatArray:(IOSFloatArray *)sxys
                                   withJavaLangIntegerArray:(IOSIntArray *)indices;
- (id<PlaynCoreSurface>)restore;
- (id<PlaynCoreSurface>)rotateWithFloat:(float)angle;
- (id<PlaynCoreSurface>)save;
- (id<PlaynCoreSurface>)scale__WithFloat:(float)sx
                               withFloat:(float)sy;
- (id<PlaynCoreSurface>)setTransformWithFloat:(float)m00
                                    withFloat:(float)m01
                                    withFloat:(float)m10
                                    withFloat:(float)m11
                                    withFloat:(float)tx
                                    withFloat:(float)ty;
- (id<PlaynCoreSurface>)setAlphaWithFloat:(float)alpha;
- (id<PlaynCoreSurface>)setTintWithInt:(int)tint;
- (id<PlaynCoreSurface>)setFillColorWithInt:(int)color;
- (id<PlaynCoreSurface>)setFillPatternWithPlaynCorePattern:(id<PlaynCorePattern>)pattern;
- (id<PlaynCoreSurface>)setShaderWithPlaynCoreGlGLShader:(PlaynCoreGlGLShader *)shader;
- (id<PlaynCoreSurface>)transformWithFloat:(float)m00
                                 withFloat:(float)m01
                                 withFloat:(float)m10
                                 withFloat:(float)m11
                                 withFloat:(float)tx
                                 withFloat:(float)ty;
- (id<PlaynCoreSurface>)translateWithFloat:(float)x
                                 withFloat:(float)y;
- (id<PlaynCoreInternalTransform>)topTransform;
- (float)height;
- (float)width;
@end
