//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: C:\Users\Thomas\Documents\Eclipse\Tux\tuxblocks\core\src\main\java\tuxkids\tuxblocks\core\defense\round\Reward.java
//
//  Created by Thomas on 7/1/13.
//

#import "tuxkids/tuxblocks/core/defense/round/Reward.h"
#import "tuxkids/tuxblocks/core/defense/tower/TowerType.h"

@implementation TBReward

- (TBTowerTypeEnum *)tower {
  return tower_;
}
- (void)setTower:(TBTowerTypeEnum *)tower {
  JreOperatorRetainedAssign(&tower_, self, tower);
}
@synthesize tower = tower_;
@synthesize count = count_;

- (id)initWithTBTowerTypeEnum:(TBTowerTypeEnum *)tower
                      withInt:(int)count {
  if ((self = [super init])) {
    self.tower = tower;
    self.count = count;
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&tower_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TBReward *typedCopy = (TBReward *) copy;
  typedCopy.tower = tower_;
  typedCopy.count = count_;
}

@end
