//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: C:\Users\Thomas\Documents\Eclipse\Tux\tuxblocks\core\src\main\java\tuxkids\tuxblocks\core\defense\round\Wave.java
//
//  Created by Thomas on 7/1/13.
//

@class TBWalker;

#import "JreEmulation.h"

@interface TBWave : NSObject {
 @public
  TBWalker *walker__;
  int interval__;
  int count__;
  int timer_;
  int produced_;
}

@property (nonatomic, retain) TBWalker *walker_;
@property (nonatomic, assign) int interval_;
@property (nonatomic, assign) int count_;
@property (nonatomic, assign) int timer;
@property (nonatomic, assign) int produced;

- (TBWalker *)walker;
- (int)interval;
- (int)count;
- (id)initWithTBWalker:(TBWalker *)walker
               withInt:(int)interval
               withInt:(int)count;
- (TBWalker *)updateWithInt:(int)delta;
- (BOOL)finished;
@end

typedef TBWave TuxkidsTuxblocksCoreDefenseRoundWave;
