//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: C:\Users\Thomas\Documents\Eclipse\Tux\tuxblocks\core\src\main\java\tuxkids\tuxblocks\core\solve\NumberSelectScreen.java
//
//  Created by Thomas on 7/1/13.
//

#import "java/lang/Double.h"
#import "java/lang/Integer.h"
#import "java/lang/Math.h"
#import "java/util/ArrayList.h"
#import "java/util/List.h"
#import "playn/core/Assets.h"
#import "playn/core/Canvas.h"
#import "playn/core/CanvasImage.h"
#import "playn/core/Color.h"
#import "playn/core/Connection.h"
#import "playn/core/Events.h"
#import "playn/core/Font.h"
#import "playn/core/Graphics.h"
#import "playn/core/GroupLayer.h"
#import "playn/core/Image.h"
#import "playn/core/ImageLayer.h"
#import "playn/core/Layer.h"
#import "playn/core/PlayN.h"
#import "playn/core/Pointer.h"
#import "playn/core/TextFormat.h"
#import "playn/core/TextLayout.h"
#import "playn/core/util/Clock.h"
#import "pythagoras/f/FloatMath.h"
#import "pythagoras/f/Point.h"
#import "pythagoras/f/Vector.h"
#import "pythagoras/i/Point.h"
#import "tripleplay/game/Screen.h"
#import "tripleplay/game/ScreenStack.h"
#import "tripleplay/util/Colors.h"
#import "tuxkids/tuxblocks/core/Button.h"
#import "tuxkids/tuxblocks/core/Constant.h"
#import "tuxkids/tuxblocks/core/GameBackgroundSprite.h"
#import "tuxkids/tuxblocks/core/GameState.h"
#import "tuxkids/tuxblocks/core/ImageLayerTintable.h"
#import "tuxkids/tuxblocks/core/MenuSprite.h"
#import "tuxkids/tuxblocks/core/PlayNObject.h"
#import "tuxkids/tuxblocks/core/screen/GameScreen.h"
#import "tuxkids/tuxblocks/core/solve/NumberSelectScreen.h"
#import "tuxkids/tuxblocks/core/utils/CanvasUtils.h"

@implementation TBNumberSelectScreen

static NSString * TBNumberSelectScreen_PLACEHOLDER_ = @"%";

@synthesize SPACING = SPACING_;
- (id<JavaUtilList>)numberPoints {
  return numberPoints_;
}
- (void)setNumberPoints:(id<JavaUtilList>)numberPoints {
  JreOperatorRetainedAssign(&numberPoints_, self, numberPoints);
}
@synthesize numberPoints = numberPoints_;
- (id<JavaUtilList>)numberImages {
  return numberImages_;
}
- (void)setNumberImages:(id<JavaUtilList>)numberImages {
  JreOperatorRetainedAssign(&numberImages_, self, numberImages);
}
@synthesize numberImages = numberImages_;
- (PlaynCoreTextFormat *)textFormat {
  return textFormat_;
}
- (void)setTextFormat:(PlaynCoreTextFormat *)textFormat {
  JreOperatorRetainedAssign(&textFormat_, self, textFormat);
}
@synthesize textFormat = textFormat_;
- (PlaynCoreTextFormat *)equationFormat {
  return equationFormat_;
}
- (void)setEquationFormat:(PlaynCoreTextFormat *)equationFormat {
  JreOperatorRetainedAssign(&equationFormat_, self, equationFormat);
}
@synthesize equationFormat = equationFormat_;
- (PythagorasIPoint *)selectedPoint {
  return selectedPoint_;
}
- (void)setSelectedPoint:(PythagorasIPoint *)selectedPoint {
  JreOperatorRetainedAssign(&selectedPoint_, self, selectedPoint);
}
@synthesize selectedPoint = selectedPoint_;
- (PythagorasIPoint *)possibleSelectedPoint {
  return possibleSelectedPoint_;
}
- (void)setPossibleSelectedPoint:(PythagorasIPoint *)possibleSelectedPoint {
  JreOperatorRetainedAssign(&possibleSelectedPoint_, self, possibleSelectedPoint);
}
@synthesize possibleSelectedPoint = possibleSelectedPoint_;
- (PythagorasFVector *)velocity {
  return velocity_;
}
- (void)setVelocity:(PythagorasFVector *)velocity {
  JreOperatorRetainedAssign(&velocity_, self, velocity);
}
@synthesize velocity = velocity_;
- (PythagorasFVector *)position {
  return position_;
}
- (void)setPosition:(PythagorasFVector *)position {
  JreOperatorRetainedAssign(&position_, self, position);
}
@synthesize position = position_;
- (PythagorasFVector *)lastPosition {
  return lastPosition_;
}
- (void)setLastPosition:(PythagorasFVector *)lastPosition {
  JreOperatorRetainedAssign(&lastPosition_, self, lastPosition);
}
@synthesize lastPosition = lastPosition_;
- (PythagorasFVector *)dragOffset {
  return dragOffset_;
}
- (void)setDragOffset:(PythagorasFVector *)dragOffset {
  JreOperatorRetainedAssign(&dragOffset_, self, dragOffset);
}
@synthesize dragOffset = dragOffset_;
- (id<JavaUtilList>)positionTrail {
  return positionTrail_;
}
- (void)setPositionTrail:(id<JavaUtilList>)positionTrail {
  JreOperatorRetainedAssign(&positionTrail_, self, positionTrail);
}
@synthesize positionTrail = positionTrail_;
- (id<JavaUtilList>)timeTrail {
  return timeTrail_;
}
- (void)setTimeTrail:(id<JavaUtilList>)timeTrail {
  JreOperatorRetainedAssign(&timeTrail_, self, timeTrail);
}
@synthesize timeTrail = timeTrail_;
- (id<PlaynCoreGroupLayer>)foregroundLayer {
  return foregroundLayer_;
}
- (void)setForegroundLayer:(id<PlaynCoreGroupLayer>)foregroundLayer {
  JreOperatorRetainedAssign(&foregroundLayer_, self, foregroundLayer);
}
@synthesize foregroundLayer = foregroundLayer_;
- (id<PlaynCoreGroupLayer>)backgroundLayer {
  return backgroundLayer_;
}
- (void)setBackgroundLayer:(id<PlaynCoreGroupLayer>)backgroundLayer {
  JreOperatorRetainedAssign(&backgroundLayer_, self, backgroundLayer);
}
@synthesize backgroundLayer = backgroundLayer_;
- (id<PlaynCoreGroupLayer>)equationLayer {
  return equationLayer_;
}
- (void)setEquationLayer:(id<PlaynCoreGroupLayer>)equationLayer {
  JreOperatorRetainedAssign(&equationLayer_, self, equationLayer);
}
@synthesize equationLayer = equationLayer_;
@synthesize createsSpritesThisFrame = createsSpritesThisFrame_;
@synthesize themeColor = themeColor_;
@synthesize equationHeight = equationHeight_;
@synthesize equationBlankX = equationBlankX_;
- (id<PlaynCoreImageLayer>)equationAnswer {
  return equationAnswer_;
}
- (void)setEquationAnswer:(id<PlaynCoreImageLayer>)equationAnswer {
  JreOperatorRetainedAssign(&equationAnswer_, self, equationAnswer);
}
@synthesize equationAnswer = equationAnswer_;
- (PythagorasIPoint *)equationAnswerPoint {
  return equationAnswerPoint_;
}
- (void)setEquationAnswerPoint:(PythagorasIPoint *)equationAnswerPoint {
  JreOperatorRetainedAssign(&equationAnswerPoint_, self, equationAnswerPoint);
}
@synthesize equationAnswerPoint = equationAnswerPoint_;
- (NSString *)expression {
  return expression_;
}
- (void)setExpression:(NSString *)expression {
  JreOperatorRetainedAssign(&expression_, self, expression);
}
@synthesize expression = expression_;
@synthesize answer = answer_;
- (TBButton *)buttonBack {
  return buttonBack_;
}
- (void)setButtonBack:(TBButton *)buttonBack {
  JreOperatorRetainedAssign(&buttonBack_, self, buttonBack);
}
@synthesize buttonBack = buttonBack_;
- (TBButton *)buttonCenter {
  return buttonCenter_;
}
- (void)setButtonCenter:(TBButton *)buttonCenter {
  JreOperatorRetainedAssign(&buttonCenter_, self, buttonCenter);
}
@synthesize buttonCenter = buttonCenter_;
- (id<PlaynCoreImage>)backImageOk {
  return backImageOk_;
}
- (void)setBackImageOk:(id<PlaynCoreImage>)backImageOk {
  JreOperatorRetainedAssign(&backImageOk_, self, backImageOk);
}
@synthesize backImageOk = backImageOk_;
- (id<PlaynCoreImage>)backImageBack {
  return backImageBack_;
}
- (void)setBackImageBack:(id<PlaynCoreImage>)backImageBack {
  JreOperatorRetainedAssign(&backImageBack_, self, backImageBack);
}
@synthesize backImageBack = backImageBack_;
- (id<PlaynCoreImage>)backImageCancel {
  return backImageCancel_;
}
- (void)setBackImageCancel:(id<PlaynCoreImage>)backImageCancel {
  JreOperatorRetainedAssign(&backImageCancel_, self, backImageCancel);
}
@synthesize backImageCancel = backImageCancel_;
- (PythagorasIPoint *)recenterPoint {
  return recenterPoint_;
}
- (void)setRecenterPoint:(PythagorasIPoint *)recenterPoint {
  JreOperatorRetainedAssign(&recenterPoint_, self, recenterPoint);
}
@synthesize recenterPoint = recenterPoint_;
- (TBImageLayerTintable *)selectedNumberLayer {
  return selectedNumberLayer_;
}
- (void)setSelectedNumberLayer:(TBImageLayerTintable *)selectedNumberLayer {
  JreOperatorRetainedAssign(&selectedNumberLayer_, self, selectedNumberLayer);
}
@synthesize selectedNumberLayer = selectedNumberLayer_;
- (TBMenuSprite *)menu {
  return menu_;
}
- (void)setMenu:(TBMenuSprite *)menu {
  JreOperatorRetainedAssign(&menu_, self, menu);
}
@synthesize menu = menu_;
@synthesize dragging = dragging_;

+ (NSString *)PLACEHOLDER {
  return TBNumberSelectScreen_PLACEHOLDER_;
}

- (JavaLangInteger *)selectedAnswer {
  if (selectedPoint_ == nil) return nil;
  return [JavaLangInteger valueOfWithInt:[self getNumberWithPythagorasIPoint:selectedPoint_]];
}

- (BOOL)hasCorrectAnswer {
  JavaLangInteger *answer = [self selectedAnswer];
  return answer != nil && [((JavaLangInteger *) NIL_CHK(answer)) intValue] == self.answer;
}

- (void)setFocusedNumberWithInt:(int)number {
  JreOperatorRetainedAssign(&recenterPoint_, self, [self getPointWithInt:number]);
}

- (id)initWithTripleplayGameScreenStack:(TripleplayGameScreenStack *)screens
                        withTBGameState:(TBGameState *)gameState
                           withNSString:(NSString *)expression
                                withInt:(int)answer {
  if ((self = [super initWithTripleplayGameScreenStack:screens withTBGameState:gameState])) {
    SPACING_ = 150;
    JreOperatorRetainedAssign(&numberPoints_, self, [[[JavaUtilArrayList alloc] init] autorelease]);
    JreOperatorRetainedAssign(&numberImages_, self, [[[JavaUtilArrayList alloc] init] autorelease]);
    JreOperatorRetainedAssign(&velocity_, self, [[[PythagorasFVector alloc] init] autorelease]);
    JreOperatorRetainedAssign(&position_, self, [[[PythagorasFVector alloc] init] autorelease]);
    JreOperatorRetainedAssign(&lastPosition_, self, [[[PythagorasFVector alloc] init] autorelease]);
    JreOperatorRetainedAssign(&dragOffset_, self, [[[PythagorasFVector alloc] init] autorelease]);
    JreOperatorRetainedAssign(&positionTrail_, self, [[[JavaUtilArrayList alloc] init] autorelease]);
    JreOperatorRetainedAssign(&timeTrail_, self, [[[JavaUtilArrayList alloc] init] autorelease]);
    JreOperatorRetainedAssign(&recenterPoint_, self, [[[PythagorasIPoint alloc] init] autorelease]);
    self.expression = expression;
    self.answer = answer;
  }
  return self;
}

- (void)wasAdded {
  [super wasAdded];
  themeColor_ = [((TBGameState *) NIL_CHK(state__)) themeColor];
  SPACING_ = (int) ([self height] / 3.5f);
  (void) [((PythagorasFVector *) NIL_CHK(position_)) setWithFloat:((PythagorasIPoint *) NIL_CHK(recenterPoint_)).x_ * SPACING_ withFloat:((PythagorasIPoint *) NIL_CHK(recenterPoint_)).y_ * SPACING_];
  (void) [((PythagorasFVector *) NIL_CHK(lastPosition_)) setWithPythagorasFIVector:position_];
  JreOperatorRetainedAssign(&textFormat_, self, [((PlaynCoreTextFormat *) [[[PlaynCoreTextFormat alloc] init] autorelease]) withFontWithPlaynCoreFont:[((id<PlaynCoreGraphics>) [TBGameScreen graphics]) createFontWithNSString:[TBConstant FONT_NAME] withPlaynCoreFont_StyleEnum:[PlaynCoreFont_StyleEnum PLAIN] withFloat:SPACING_ / 3]]);
  JreOperatorRetainedAssign(&equationFormat_, self, [((PlaynCoreTextFormat *) [[[PlaynCoreTextFormat alloc] init] autorelease]) withFontWithPlaynCoreFont:[((id<PlaynCoreGraphics>) [TBGameScreen graphics]) createFontWithNSString:[TBConstant FONT_NAME] withPlaynCoreFont_StyleEnum:[PlaynCoreFont_StyleEnum PLAIN] withFloat:SPACING_ / 3 * 0.8f]]);
  JreOperatorRetainedAssign(&backgroundLayer_, self, [((id<PlaynCoreGraphics>) [TBGameScreen graphics]) createGroupLayer]);
  JreOperatorRetainedAssign(&foregroundLayer_, self, [((id<PlaynCoreGraphics>) [TBGameScreen graphics]) createGroupLayer]);
  [((id<PlaynCoreGroupLayer>) NIL_CHK(layer_)) addWithPlaynCoreLayer:foregroundLayer_];
  [((id<PlaynCorePointer>) [PlaynCorePlayN pointer]) setListenerWithPlaynCorePointer_Listener:self];
  [self createBackground];
  [self createEquationWithNSString:expression_];
  (void) [((id<PlaynCoreGroupLayer>) NIL_CHK(foregroundLayer_)) setOriginWithFloat:-[self width] / 2 withFloat:-[self height] / 2 - equationHeight_ / 2];
  (void) [((id<PlaynCoreGroupLayer>) NIL_CHK(backgroundLayer_)) setTranslationWithFloat:0 withFloat:equationHeight_ / 2];
  JreOperatorRetainedAssign(&selectedNumberLayer_, self, [[[TBImageLayerTintable alloc] init] autorelease]);
  [((TBImageLayerTintable *) NIL_CHK(selectedNumberLayer_)) setDepthWithFloat:10];
  [((TBImageLayerTintable *) NIL_CHK(selectedNumberLayer_)) setTintWithInt:themeColor_];
  [((id<PlaynCoreGroupLayer>) NIL_CHK(foregroundLayer_)) addWithPlaynCoreLayer:[((TBImageLayerTintable *) NIL_CHK(selectedNumberLayer_)) layer]];
  [self updateWithInt:0];
}

- (void)createEquationWithNSString:(NSString *)equation {
  JreOperatorRetainedAssign(&menu_, self, [[[TBMenuSprite alloc] initWithFloat:[self width] withFloat:[TBGameScreen defaultButtonSize] * 1.2f] autorelease]);
  int index = [NIL_CHK(equation) indexOfString:TBNumberSelectScreen_PLACEHOLDER_];
  NSString *before = [NIL_CHK(equation) substring:0 endIndex:index];
  NSString *after = [NIL_CHK(equation) substring:index + 1];
  id<PlaynCoreTextLayout> sampleNumber = [((id<PlaynCoreGraphics>) [TBGameScreen graphics]) layoutTextWithNSString:@"-999" withPlaynCoreTextFormat:equationFormat_];
  int boxSpace = 10;
  float boxWidth = [((id<PlaynCoreTextLayout>) NIL_CHK(sampleNumber)) width] + boxSpace;
  float boxHeight = [TBGameScreen defaultButtonSize];
  float width = 0, height = 0;
  id<PlaynCoreTextLayout> beforeLayout = nil, afterLayout = nil;
  if (![NIL_CHK(before) isEmpty]) {
    beforeLayout = [((id<PlaynCoreGraphics>) [TBGameScreen graphics]) layoutTextWithNSString:before withPlaynCoreTextFormat:equationFormat_];
    width += [((id<PlaynCoreTextLayout>) NIL_CHK(beforeLayout)) width] + boxSpace;
    height = [JavaLangMath maxWithFloat:[((id<PlaynCoreTextLayout>) NIL_CHK(beforeLayout)) height] withFloat:height];
  }
  if (![NIL_CHK(after) isEmpty]) {
    afterLayout = [((id<PlaynCoreGraphics>) [TBGameScreen graphics]) layoutTextWithNSString:after withPlaynCoreTextFormat:equationFormat_];
    width += [((id<PlaynCoreTextLayout>) NIL_CHK(afterLayout)) width] + boxSpace;
    height = [JavaLangMath maxWithFloat:[((id<PlaynCoreTextLayout>) NIL_CHK(afterLayout)) height] withFloat:height];
  }
  width += boxWidth + boxSpace * 2;
  height = [JavaLangMath maxWithFloat:boxHeight withFloat:height];
  id<PlaynCoreCanvasImage> eqImage = [((id<PlaynCoreGraphics>) [TBGameScreen graphics]) createImageWithFloat:width withFloat:height];
  id<PlaynCoreCanvas> canvas = [((id<PlaynCoreCanvasImage>) NIL_CHK(eqImage)) canvas];
  float x = 0;
  (void) [((id<PlaynCoreCanvas>) NIL_CHK(canvas)) setFillColorWithInt:[TripleplayUtilColors BLACK]];
  if (beforeLayout != nil) {
    (void) [((id<PlaynCoreCanvas>) NIL_CHK(canvas)) fillTextWithPlaynCoreTextLayout:beforeLayout withFloat:x withFloat:(height - [beforeLayout height]) / 2];
    x += [beforeLayout width] + boxSpace;
  }
  (void) [((id<PlaynCoreCanvas>) NIL_CHK(canvas)) setFillColorWithInt:[PlaynCoreColor withAlphaWithInt:themeColor_ withInt:100]];
  (void) [((id<PlaynCoreCanvas>) NIL_CHK(canvas)) setStrokeColorWithInt:themeColor_];
  (void) [((id<PlaynCoreCanvas>) NIL_CHK(canvas)) fillRectWithFloat:x withFloat:(height - boxHeight) / 2 withFloat:boxWidth withFloat:boxHeight];
  (void) [((id<PlaynCoreCanvas>) NIL_CHK(canvas)) strokeRectWithFloat:x withFloat:(height - boxHeight) / 2 withFloat:boxWidth - 0.5f withFloat:boxHeight - 0.5f];
  equationBlankX_ = x + boxWidth / 2;
  x += boxWidth + boxSpace;
  (void) [((id<PlaynCoreCanvas>) NIL_CHK(canvas)) setFillColorWithInt:[TripleplayUtilColors BLACK]];
  if (afterLayout != nil) {
    (void) [((id<PlaynCoreCanvas>) NIL_CHK(canvas)) fillTextWithPlaynCoreTextLayout:afterLayout withFloat:x withFloat:(height - [afterLayout height]) / 2];
  }
  id<PlaynCoreImageLayer> eqLayer = [((id<PlaynCoreGraphics>) [TBGameScreen graphics]) createImageLayerWithPlaynCoreImage:eqImage];
  (void) [((id<PlaynCoreImageLayer>) NIL_CHK(eqLayer)) setTranslationWithFloat:([self width] - [((id<PlaynCoreImageLayer>) NIL_CHK(eqLayer)) width]) / 2 withFloat:([((TBMenuSprite *) NIL_CHK(menu_)) height] - [((id<PlaynCoreImageLayer>) NIL_CHK(eqLayer)) height]) / 2];
  JreOperatorRetainedAssign(&backImageOk_, self, [((id<PlaynCoreAssets>) [PlaynCorePlayN assets]) getImageWithNSString:@"images/ok.png"]);
  JreOperatorRetainedAssign(&backImageBack_, self, [((id<PlaynCoreAssets>) [PlaynCorePlayN assets]) getImageWithNSString:@"images/back.png"]);
  JreOperatorRetainedAssign(&backImageCancel_, self, [((id<PlaynCoreAssets>) [PlaynCorePlayN assets]) getImageWithNSString:@"images/cancel.png"]);
  float bgHeight = [((TBMenuSprite *) NIL_CHK(menu_)) height];
  float buttonHeight = [TBGameScreen defaultButtonSize];
  JreOperatorRetainedAssign(&buttonBack_, self, [[[TBButton alloc] initWithPlaynCoreImage:backImageBack_ withFloat:buttonHeight withFloat:buttonHeight withBOOL:YES] autorelease]);
  [((TBButton *) NIL_CHK(buttonBack_)) setPositionWithFloat:[((TBButton *) NIL_CHK(buttonBack_)) width] / 2 + 10 withFloat:bgHeight / 2];
  [((TBButton *) NIL_CHK(buttonBack_)) setTintWithInt:themeColor_ withFloat:TBButton_UNPRESSED_ALPHA];
  [((TBButton *) NIL_CHK(buttonBack_)) setOnReleasedListenerWithTBButton_OnReleasedListener:[[[TBNumberSelectScreen_$1 alloc] initWithTBNumberSelectScreen:self] autorelease]];
  JreOperatorRetainedAssign(&buttonCenter_, self, [[[TBButton alloc] initWithNSString:@"images/center.png" withFloat:buttonHeight withFloat:buttonHeight withBOOL:YES] autorelease]);
  [((TBButton *) NIL_CHK(buttonCenter_)) setPositionWithFloat:[self width] - [((TBButton *) NIL_CHK(buttonCenter_)) width] / 2 - 10 withFloat:bgHeight / 2];
  [((TBButton *) NIL_CHK(buttonCenter_)) setTintWithInt:themeColor_ withFloat:TBButton_UNPRESSED_ALPHA];
  [((TBButton *) NIL_CHK(buttonCenter_)) setOnReleasedListenerWithTBButton_OnReleasedListener:[[[TBNumberSelectScreen_$2 alloc] initWithTBNumberSelectScreen:self] autorelease]];
  JreOperatorRetainedAssign(&equationLayer_, self, [((id<PlaynCoreGraphics>) [TBGameScreen graphics]) createGroupLayer]);
  [((id<PlaynCoreGroupLayer>) NIL_CHK(equationLayer_)) addWithPlaynCoreLayer:[((TBMenuSprite *) NIL_CHK(menu_)) layer]];
  [((id<PlaynCoreGroupLayer>) NIL_CHK(equationLayer_)) addWithPlaynCoreLayer:eqLayer];
  [((id<PlaynCoreGroupLayer>) NIL_CHK(equationLayer_)) addWithPlaynCoreLayer:[((TBButton *) NIL_CHK(buttonBack_)) layerAddable]];
  [((id<PlaynCoreGroupLayer>) NIL_CHK(equationLayer_)) addWithPlaynCoreLayer:[((TBButton *) NIL_CHK(buttonCenter_)) layerAddable]];
  equationHeight_ = [((TBMenuSprite *) NIL_CHK(menu_)) height];
  equationBlankX_ += [((id<PlaynCoreImageLayer>) NIL_CHK(eqLayer)) tx];
  [((id<PlaynCoreGroupLayer>) NIL_CHK(layer_)) addWithPlaynCoreLayer:equationLayer_];
}

- (void)updateEquationAnswer {
  if (selectedPoint_ == nil && equationAnswer_ != nil) {
    [((id<PlaynCoreGroupLayer>) NIL_CHK(equationLayer_)) removeWithPlaynCoreLayer:equationAnswer_];
    JreOperatorRetainedAssign(&equationAnswer_, self, nil);
    JreOperatorRetainedAssign(&equationAnswerPoint_, self, nil);
    [((TBButton *) NIL_CHK(buttonBack_)) setImageWithPlaynCoreImage:backImageBack_];
  }
  else if (selectedPoint_ != nil && ![((PythagorasIPoint *) NIL_CHK(selectedPoint_)) isEqual:equationAnswerPoint_]) {
    JreOperatorRetainedAssign(&equationAnswerPoint_, self, [[[PythagorasIPoint alloc] initWithPythagorasIIPoint:selectedPoint_] autorelease]);
    if (equationAnswer_ != nil) [((id<PlaynCoreGroupLayer>) NIL_CHK(equationLayer_)) removeWithPlaynCoreLayer:equationAnswer_];
    NSString *text = [NSString stringWithFormat:@"%d", [self getNumberWithPythagorasIPoint:selectedPoint_]];
    id<PlaynCoreCanvasImage> image = [TBCanvasUtils createTextWithNSString:text withPlaynCoreTextFormat:equationFormat_ withInt:[TripleplayUtilColors BLACK]];
    JreOperatorRetainedAssign(&equationAnswer_, self, [((id<PlaynCoreGraphics>) [TBGameScreen graphics]) createImageLayerWithPlaynCoreImage:image]);
    (void) [((id<PlaynCoreImageLayer>) NIL_CHK(equationAnswer_)) setOriginWithFloat:[((id<PlaynCoreImageLayer>) NIL_CHK(equationAnswer_)) width] / 2 withFloat:[((id<PlaynCoreImageLayer>) NIL_CHK(equationAnswer_)) height] / 2];
    (void) [((id<PlaynCoreImageLayer>) NIL_CHK(equationAnswer_)) setTranslationWithFloat:equationBlankX_ withFloat:equationHeight_ / 2];
    [((id<PlaynCoreGroupLayer>) NIL_CHK(equationLayer_)) addWithPlaynCoreLayer:equationAnswer_];
    [((TBButton *) NIL_CHK(buttonBack_)) setImageWithPlaynCoreImage:backImageOk_];
  }
}

- (void)createBackground {
  (void) [((id<PlaynCoreGroupLayer>) NIL_CHK(backgroundLayer_)) setDepthWithFloat:-100];
  id<PlaynCoreCanvasImage> circleImage = [TBCanvasUtils createCircleWithFloat:SPACING_ / 2 withInt:[PlaynCoreColor argbWithInt:0 withInt:0 withInt:0 withInt:0] withFloat:20 withInt:[TripleplayUtilColors WHITE]];
  id<PlaynCoreImageLayer> circle = [((id<PlaynCoreGraphics>) [TBGameScreen graphics]) createImageLayerWithPlaynCoreImage:circleImage];
  (void) [((id<PlaynCoreImageLayer>) NIL_CHK(circle)) setOriginWithFloat:[((id<PlaynCoreCanvasImage>) NIL_CHK(circleImage)) width] / 2 withFloat:[((id<PlaynCoreCanvasImage>) NIL_CHK(circleImage)) height] / 2];
  (void) [((id<PlaynCoreImageLayer>) NIL_CHK(circle)) setTranslationWithFloat:[self width] / 2 withFloat:[self height] / 2];
  (void) [((id<PlaynCoreImageLayer>) NIL_CHK(circle)) setAlphaWithFloat:0.7f];
  (void) [((id<PlaynCoreImageLayer>) NIL_CHK(circle)) setDepthWithFloat:0];
  [((id<PlaynCoreGroupLayer>) NIL_CHK(backgroundLayer_)) addWithPlaynCoreLayer:circle];
  [((id<PlaynCoreGroupLayer>) NIL_CHK(layer_)) addWithPlaynCoreLayer:backgroundLayer_];
}

- (void)updateWithInt:(int)delta {
  [super updateWithInt:delta];
  int left = (int) ((((PythagorasFVector *) NIL_CHK(position_)).x_ - [self width] / 2) / SPACING_ - 0.5);
  int right = (int) ((((PythagorasFVector *) NIL_CHK(position_)).x_ + [self width] / 2) / SPACING_ + 0.5);
  int top = (int) ((((PythagorasFVector *) NIL_CHK(position_)).y_ - [self height] / 2) / SPACING_ - 0.5);
  int bot = (int) ((((PythagorasFVector *) NIL_CHK(position_)).y_ + [self height] / 2) / SPACING_ + 0.5);
  [self updateEquationAnswer];
  createsSpritesThisFrame_ = 0;
  PythagorasIPoint *p = [[[PythagorasIPoint alloc] init] autorelease];
  for (int i = left; i <= right; i++) {
    for (int j = top; j <= bot; j++) {
      [((PythagorasIPoint *) NIL_CHK(p)) setLocationWithInt:i withInt:j];
      (void) [self createNumberSpriteWithPythagorasIPoint:p];
    }
  }
}

- (void)paintWithPlaynCoreUtilClock:(id<PlaynCoreUtilClock>)clock {
  [super paintWithPlaynCoreUtilClock:clock];
  [[((TBGameState *) NIL_CHK(state__)) background] scrollWithFloat:((PythagorasFVector *) NIL_CHK(lastPosition_)).x_ - ((PythagorasFVector *) NIL_CHK(position_)).x_ withFloat:((PythagorasFVector *) NIL_CHK(lastPosition_)).y_ - ((PythagorasFVector *) NIL_CHK(position_)).y_];
  (void) [((PythagorasFVector *) NIL_CHK(lastPosition_)) setWithPythagorasFIVector:position_];
  [self updateEquationAnswer];
  [((TBImageLayerTintable *) NIL_CHK(selectedNumberLayer_)) setVisibleWithBOOL:NO];
  for (int i = 0; i < [((id<JavaUtilList>) NIL_CHK(numberImages_)) size]; i++) {
    id<PlaynCoreImageLayer> layer = ((id<PlaynCoreImageLayer>) [((id<JavaUtilList>) NIL_CHK(numberImages_)) getWithInt:i]);
    PythagorasIPoint *p = ((PythagorasIPoint *) [((id<JavaUtilList>) NIL_CHK(numberPoints_)) getWithInt:i]);
    float dx = ((PythagorasFVector *) NIL_CHK(position_)).x_ - ((PythagorasIPoint *) NIL_CHK(p)).x_ * SPACING_;
    float dy = ((PythagorasFVector *) NIL_CHK(position_)).y_ - ((PythagorasIPoint *) NIL_CHK(p)).y_ * SPACING_;
    float distance = [PythagorasFFloatMath sqrtWithFloat:dx * dx + dy * dy];
    float alpha = 1 - [JavaLangMath minWithFloat:distance / SPACING_ / 5 withFloat:1];
    float preAlpha = [((id<PlaynCoreImageLayer>) NIL_CHK(layer)) alpha];
    if ([((PythagorasIPoint *) NIL_CHK(p)) isEqual:selectedPoint_]) {
      [((TBImageLayerTintable *) NIL_CHK(selectedNumberLayer_)) setImageWithPlaynCoreImage:[((id<PlaynCoreImageLayer>) NIL_CHK(layer)) image]];
      [((TBImageLayerTintable *) NIL_CHK(selectedNumberLayer_)) setTranslationWithFloat:[((id<PlaynCoreImageLayer>) NIL_CHK(layer)) tx] withFloat:[((id<PlaynCoreImageLayer>) NIL_CHK(layer)) ty]];
      [((TBImageLayerTintable *) NIL_CHK(selectedNumberLayer_)) setOriginWithFloat:[((id<PlaynCoreImageLayer>) NIL_CHK(layer)) width] / 2 withFloat:[((id<PlaynCoreImageLayer>) NIL_CHK(layer)) height] / 2];
      [((TBImageLayerTintable *) NIL_CHK(selectedNumberLayer_)) setVisibleWithBOOL:YES];
      (void) [((id<PlaynCoreImageLayer>) NIL_CHK(layer)) setVisibleWithBOOL:NO];
    }
    else {
      (void) [((id<PlaynCoreImageLayer>) NIL_CHK(layer)) setVisibleWithBOOL:YES];
    }
    (void) [((id<PlaynCoreImageLayer>) NIL_CHK(layer)) setAlphaWithFloat:[TBPlayNObject lerpTimeWithFloat:preAlpha withFloat:alpha withFloat:0.995f withFloat:[((id<PlaynCoreUtilClock>) NIL_CHK(clock)) dt]]];
  }
  if (selectedPoint_ == nil) {
    ((PythagorasFVector *) NIL_CHK(position_)).x_ += ((PythagorasFVector *) NIL_CHK(velocity_)).x_ * [((id<PlaynCoreUtilClock>) NIL_CHK(clock)) dt];
    ((PythagorasFVector *) NIL_CHK(position_)).y_ += ((PythagorasFVector *) NIL_CHK(velocity_)).y_ * [((id<PlaynCoreUtilClock>) NIL_CHK(clock)) dt];
    ((PythagorasFVector *) NIL_CHK(velocity_)).x_ *= [JavaLangMath powWithDouble:0.995 withDouble:[((id<PlaynCoreUtilClock>) NIL_CHK(clock)) dt]];
    ((PythagorasFVector *) NIL_CHK(velocity_)).y_ *= [JavaLangMath powWithDouble:0.995 withDouble:[((id<PlaynCoreUtilClock>) NIL_CHK(clock)) dt]];
  }
  else {
    [TBPlayNObject lerpTimeWithPythagorasFVector:position_ withInt:selectedPoint_.x_ * SPACING_ withInt:selectedPoint_.y_ * SPACING_ withFloat:0.99f withFloat:[((id<PlaynCoreUtilClock>) NIL_CHK(clock)) dt]];
  }
  (void) [((id<PlaynCoreGroupLayer>) NIL_CHK(foregroundLayer_)) setTranslationWithFloat:-((PythagorasFVector *) NIL_CHK(position_)).x_ withFloat:-((PythagorasFVector *) NIL_CHK(position_)).y_];
}

- (id<PlaynCoreImageLayer>)createNumberSpriteWithPythagorasIPoint:(PythagorasIPoint *)p {
  int index = [((id<JavaUtilList>) NIL_CHK(numberPoints_)) indexOfWithId:p];
  if (index >= 0) {
    id<PlaynCoreImageLayer> layer = ((id<PlaynCoreImageLayer>) [((id<JavaUtilList>) NIL_CHK(numberImages_)) removeWithInt:index]);
    [((id<JavaUtilList>) NIL_CHK(numberImages_)) addWithId:layer];
    PythagorasIPoint *point = ((PythagorasIPoint *) [((id<JavaUtilList>) NIL_CHK(numberPoints_)) removeWithInt:index]);
    [((id<JavaUtilList>) NIL_CHK(numberPoints_)) addWithId:point];
    return layer;
  }
  if (createsSpritesThisFrame_ == TBNumberSelectScreen_MAX_SPRITE_CREATE_PER_FRAME) {
    return nil;
  }
  createsSpritesThisFrame_++;
  p = [((PythagorasIPoint *) NIL_CHK(p)) clone];
  int border = 0;
  id<PlaynCoreTextLayout> layout = [((id<PlaynCoreGraphics>) [PlaynCorePlayN graphics]) layoutTextWithNSString:[NSString stringWithFormat:@"%d", [self getNumberWithPythagorasIPoint:p]] withPlaynCoreTextFormat:textFormat_];
  id<PlaynCoreCanvasImage> image = [((id<PlaynCoreGraphics>) [TBGameScreen graphics]) createImageWithFloat:[((id<PlaynCoreTextLayout>) NIL_CHK(layout)) width] + border * 2 withFloat:[((id<PlaynCoreTextLayout>) NIL_CHK(layout)) height] + border * 2];
  (void) [((id<PlaynCoreCanvas>) [((id<PlaynCoreCanvasImage>) NIL_CHK(image)) canvas]) setFillColorWithInt:[TripleplayUtilColors WHITE]];
  (void) [((id<PlaynCoreCanvas>) [((id<PlaynCoreCanvasImage>) NIL_CHK(image)) canvas]) fillTextWithPlaynCoreTextLayout:layout withFloat:border withFloat:border];
  id<PlaynCoreImageLayer> layer = [((id<PlaynCoreGraphics>) [TBGameScreen graphics]) createImageLayerWithPlaynCoreImage:image];
  (void) [((id<PlaynCoreImageLayer>) NIL_CHK(layer)) setOriginWithFloat:[((id<PlaynCoreCanvasImage>) NIL_CHK(image)) width] / 2 withFloat:[((id<PlaynCoreCanvasImage>) NIL_CHK(image)) height] / 2];
  (void) [((id<PlaynCoreImageLayer>) NIL_CHK(layer)) setTranslationWithFloat:((PythagorasIPoint *) NIL_CHK(p)).x_ * SPACING_ withFloat:((PythagorasIPoint *) NIL_CHK(p)).y_ * SPACING_];
  (void) [((id<PlaynCoreImageLayer>) NIL_CHK(layer)) addListenerWithPlaynCorePointer_Listener:[[[TBNumberSelectScreen_NumberListener alloc] initWithTBNumberSelectScreen:self withPythagorasIPoint:p] autorelease]];
  (void) [((id<PlaynCoreImageLayer>) NIL_CHK(layer)) setAlphaWithFloat:0];
  (void) [((id<PlaynCoreImageLayer>) NIL_CHK(layer)) setHitTesterWithPlaynCoreLayer_HitTester:[[[TBNumberSelectScreen_$3 alloc] initWithTBNumberSelectScreen:self withPlaynCoreCanvasImage:image] autorelease]];
  [((id<PlaynCoreGroupLayer>) NIL_CHK(foregroundLayer_)) addWithPlaynCoreLayer:layer];
  [((id<JavaUtilList>) NIL_CHK(numberImages_)) addWithId:layer];
  [((id<JavaUtilList>) NIL_CHK(numberPoints_)) addWithId:p];
  if ([((id<JavaUtilList>) NIL_CHK(numberImages_)) size] > TBNumberSelectScreen_MAX_NUMS) {
    id<PlaynCoreImageLayer> rem = ((id<PlaynCoreImageLayer>) [((id<JavaUtilList>) NIL_CHK(numberImages_)) removeWithInt:0]);
    (void) [((id<JavaUtilList>) NIL_CHK(numberPoints_)) removeWithInt:0];
    [((id<PlaynCoreImageLayer>) NIL_CHK(rem)) destroy];
  }
  return layer;
}

- (int)getNumberWithPythagorasIPoint:(PythagorasIPoint *)p {
  return ((PythagorasIPoint *) NIL_CHK(p)).x_ - ((PythagorasIPoint *) NIL_CHK(p)).y_ * 10;
}

- (PythagorasIPoint *)getPointWithInt:(int)number {
  if (number >= 0) {
    return [[[PythagorasIPoint alloc] initWithInt:number % 10 withInt:-number / 10] autorelease];
  }
  else {
    return [[[PythagorasIPoint alloc] initWithInt:number % 10 withInt:-number / 10] autorelease];
  }
}

- (void)onPointerStartWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event {
  if ([((TBButton *) NIL_CHK(buttonBack_)) hitWithFloat:[((id<PlaynCorePointer_Event>) NIL_CHK(event)) x] withFloat:[((id<PlaynCorePointer_Event>) NIL_CHK(event)) y]] || [((TBButton *) NIL_CHK(buttonCenter_)) hitWithFloat:[((id<PlaynCorePointer_Event>) NIL_CHK(event)) x] withFloat:[((id<PlaynCorePointer_Event>) NIL_CHK(event)) y]]) {
    return;
  }
  dragging_ = YES;
  (void) [((PythagorasFVector *) NIL_CHK(dragOffset_)) setWithFloat:((PythagorasFVector *) NIL_CHK(position_)).x_ + [((id<PlaynCorePointer_Event>) NIL_CHK(event)) x] withFloat:((PythagorasFVector *) NIL_CHK(position_)).y_ + [((id<PlaynCorePointer_Event>) NIL_CHK(event)) y]];
  [((id<JavaUtilList>) NIL_CHK(positionTrail_)) clear];
  [((id<JavaUtilList>) NIL_CHK(timeTrail_)) clear];
  (void) [((PythagorasFVector *) NIL_CHK(velocity_)) setWithFloat:0 withFloat:0];
}

- (void)onPointerEndWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event {
  if (!dragging_) return;
  dragging_ = NO;
  if ([((id<JavaUtilList>) NIL_CHK(positionTrail_)) size] > 1) {
    PythagorasFVector *last = ((PythagorasFVector *) [((id<JavaUtilList>) NIL_CHK(positionTrail_)) getWithInt:0]);
    double lastTime = [((JavaLangDouble *) [((id<JavaUtilList>) NIL_CHK(timeTrail_)) getWithInt:0]) doubleValue];
    float dx = (((PythagorasFVector *) NIL_CHK(position_)).x_ - ((PythagorasFVector *) NIL_CHK(last)).x_) / (float) ([((id<PlaynCorePointer_Event>) NIL_CHK(event)) time] - lastTime);
    float dy = (((PythagorasFVector *) NIL_CHK(position_)).y_ - ((PythagorasFVector *) NIL_CHK(last)).y_) / (float) ([((id<PlaynCorePointer_Event>) NIL_CHK(event)) time] - lastTime);
    (void) [((PythagorasFVector *) NIL_CHK(velocity_)) setWithFloat:dx withFloat:dy];
    if ([((PythagorasFVector *) NIL_CHK(velocity_)) length] > 0.5f) {
      JreOperatorRetainedAssign(&possibleSelectedPoint_, self, nil);
      JreOperatorRetainedAssign(&selectedPoint_, self, nil);
    }
  }
}

- (void)onPointerDragWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event {
  if (!dragging_) return;
  (void) [((PythagorasFVector *) NIL_CHK(position_)) setWithFloat:-[((id<PlaynCorePointer_Event>) NIL_CHK(event)) x] + ((PythagorasFVector *) NIL_CHK(dragOffset_)).x_ withFloat:-[((id<PlaynCorePointer_Event>) NIL_CHK(event)) y] + ((PythagorasFVector *) NIL_CHK(dragOffset_)).y_];
  [((id<JavaUtilList>) NIL_CHK(positionTrail_)) addWithId:[((PythagorasFVector *) NIL_CHK(position_)) clone]];
  [((id<JavaUtilList>) NIL_CHK(timeTrail_)) addWithId:[JavaLangDouble valueOfWithDouble:[((id<PlaynCorePointer_Event>) NIL_CHK(event)) time]]];
  if ([((id<JavaUtilList>) NIL_CHK(positionTrail_)) size] > TBNumberSelectScreen_MAX_TRAIL) {
    (void) [((id<JavaUtilList>) NIL_CHK(positionTrail_)) removeWithInt:0];
    (void) [((id<JavaUtilList>) NIL_CHK(timeTrail_)) removeWithInt:0];
    JreOperatorRetainedAssign(&selectedPoint_, self, nil);
  }
}

- (void)onPointerCancelWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event {
}

- (void)dealloc {
  JreOperatorRetainedAssign(&menu_, self, nil);
  JreOperatorRetainedAssign(&selectedNumberLayer_, self, nil);
  JreOperatorRetainedAssign(&recenterPoint_, self, nil);
  JreOperatorRetainedAssign(&backImageCancel_, self, nil);
  JreOperatorRetainedAssign(&backImageBack_, self, nil);
  JreOperatorRetainedAssign(&backImageOk_, self, nil);
  JreOperatorRetainedAssign(&buttonCenter_, self, nil);
  JreOperatorRetainedAssign(&buttonBack_, self, nil);
  JreOperatorRetainedAssign(&expression_, self, nil);
  JreOperatorRetainedAssign(&equationAnswerPoint_, self, nil);
  JreOperatorRetainedAssign(&equationAnswer_, self, nil);
  JreOperatorRetainedAssign(&equationLayer_, self, nil);
  JreOperatorRetainedAssign(&backgroundLayer_, self, nil);
  JreOperatorRetainedAssign(&foregroundLayer_, self, nil);
  JreOperatorRetainedAssign(&timeTrail_, self, nil);
  JreOperatorRetainedAssign(&positionTrail_, self, nil);
  JreOperatorRetainedAssign(&dragOffset_, self, nil);
  JreOperatorRetainedAssign(&lastPosition_, self, nil);
  JreOperatorRetainedAssign(&position_, self, nil);
  JreOperatorRetainedAssign(&velocity_, self, nil);
  JreOperatorRetainedAssign(&possibleSelectedPoint_, self, nil);
  JreOperatorRetainedAssign(&selectedPoint_, self, nil);
  JreOperatorRetainedAssign(&equationFormat_, self, nil);
  JreOperatorRetainedAssign(&textFormat_, self, nil);
  JreOperatorRetainedAssign(&numberImages_, self, nil);
  JreOperatorRetainedAssign(&numberPoints_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TBNumberSelectScreen *typedCopy = (TBNumberSelectScreen *) copy;
  typedCopy.SPACING = SPACING_;
  typedCopy.numberPoints = numberPoints_;
  typedCopy.numberImages = numberImages_;
  typedCopy.textFormat = textFormat_;
  typedCopy.equationFormat = equationFormat_;
  typedCopy.selectedPoint = selectedPoint_;
  typedCopy.possibleSelectedPoint = possibleSelectedPoint_;
  typedCopy.velocity = velocity_;
  typedCopy.position = position_;
  typedCopy.lastPosition = lastPosition_;
  typedCopy.dragOffset = dragOffset_;
  typedCopy.positionTrail = positionTrail_;
  typedCopy.timeTrail = timeTrail_;
  typedCopy.foregroundLayer = foregroundLayer_;
  typedCopy.backgroundLayer = backgroundLayer_;
  typedCopy.equationLayer = equationLayer_;
  typedCopy.createsSpritesThisFrame = createsSpritesThisFrame_;
  typedCopy.themeColor = themeColor_;
  typedCopy.equationHeight = equationHeight_;
  typedCopy.equationBlankX = equationBlankX_;
  typedCopy.equationAnswer = equationAnswer_;
  typedCopy.equationAnswerPoint = equationAnswerPoint_;
  typedCopy.expression = expression_;
  typedCopy.answer = answer_;
  typedCopy.buttonBack = buttonBack_;
  typedCopy.buttonCenter = buttonCenter_;
  typedCopy.backImageOk = backImageOk_;
  typedCopy.backImageBack = backImageBack_;
  typedCopy.backImageCancel = backImageCancel_;
  typedCopy.recenterPoint = recenterPoint_;
  typedCopy.selectedNumberLayer = selectedNumberLayer_;
  typedCopy.menu = menu_;
  typedCopy.dragging = dragging_;
}

@end
@implementation TBNumberSelectScreen_NumberListener

- (TBNumberSelectScreen *)this$0 {
  return this$0_;
}
- (void)setThis$0:(TBNumberSelectScreen *)this$0 {
  JreOperatorRetainedAssign(&this$0_, self, this$0);
}
@synthesize this$0 = this$0_;
- (PythagorasIPoint *)point {
  return point_;
}
- (void)setPoint:(PythagorasIPoint *)point {
  JreOperatorRetainedAssign(&point_, self, point);
}
@synthesize point = point_;

- (id)initWithTBNumberSelectScreen:(TBNumberSelectScreen *)outer$
              withPythagorasIPoint:(PythagorasIPoint *)point {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&this$0_, self, outer$);
    self.point = point;
  }
  return self;
}

- (void)onPointerStartWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event {
  [((id<PlaynCoreEvents_Flags>) [((id<PlaynCorePointer_Event>) NIL_CHK(event)) flags]) setPropagationStoppedWithBOOL:NO];
  this$0_.possibleSelectedPoint = point_;
}

- (void)onPointerEndWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event {
  if ([((PythagorasIPoint *) NIL_CHK(point_)) isEqual:this$0_.possibleSelectedPoint]) {
    this$0_.selectedPoint = point_;
  }
}

- (void)onPointerDragWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event {
}

- (void)onPointerCancelWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event {
}

- (void)dealloc {
  JreOperatorRetainedAssign(&point_, self, nil);
  JreOperatorRetainedAssign(&this$0_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TBNumberSelectScreen_NumberListener *typedCopy = (TBNumberSelectScreen_NumberListener *) copy;
  typedCopy.this$0 = this$0_;
  typedCopy.point = point_;
}

@end
@implementation TBNumberSelectScreen_$1

- (TBNumberSelectScreen *)this$0 {
  return this$0_;
}
- (void)setThis$0:(TBNumberSelectScreen *)this$0 {
  JreOperatorRetainedAssign(&this$0_, self, this$0);
}
@synthesize this$0 = this$0_;

- (void)onReleaseWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event
                                   withBOOL:(BOOL)inButton {
  if (inButton) {
    if (this$0_.selectedPoint != nil && [this$0_ getNumberWithPythagorasIPoint:this$0_.selectedPoint] != this$0_.answer) {
      [((TBButton *) NIL_CHK(this$0_.buttonBack)) setImageWithPlaynCoreImage:this$0_.backImageCancel];
    }
    else {
      [this$0_ popThis];
    }
  }
}

- (id)initWithTBNumberSelectScreen:(TBNumberSelectScreen *)outer$ {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&this$0_, self, outer$);
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&this$0_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TBNumberSelectScreen_$1 *typedCopy = (TBNumberSelectScreen_$1 *) copy;
  typedCopy.this$0 = this$0_;
}

@end
@implementation TBNumberSelectScreen_$2

- (TBNumberSelectScreen *)this$0 {
  return this$0_;
}
- (void)setThis$0:(TBNumberSelectScreen *)this$0 {
  JreOperatorRetainedAssign(&this$0_, self, this$0);
}
@synthesize this$0 = this$0_;

- (void)onReleaseWithPlaynCorePointer_Event:(id<PlaynCorePointer_Event>)event
                                   withBOOL:(BOOL)inButton {
  this$0_.selectedPoint = [[[PythagorasIPoint alloc] initWithPythagorasIIPoint:this$0_.recenterPoint] autorelease];
}

- (id)initWithTBNumberSelectScreen:(TBNumberSelectScreen *)outer$ {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&this$0_, self, outer$);
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&this$0_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TBNumberSelectScreen_$2 *typedCopy = (TBNumberSelectScreen_$2 *) copy;
  typedCopy.this$0 = this$0_;
}

@end
@implementation TBNumberSelectScreen_$3

- (TBNumberSelectScreen *)this$0 {
  return this$0_;
}
- (void)setThis$0:(TBNumberSelectScreen *)this$0 {
  JreOperatorRetainedAssign(&this$0_, self, this$0);
}
@synthesize this$0 = this$0_;
- (id<PlaynCoreCanvasImage>)val$image {
  return val$image_;
}
- (void)setVal$image:(id<PlaynCoreCanvasImage>)val$image {
  JreOperatorRetainedAssign(&val$image_, self, val$image);
}
@synthesize val$image = val$image_;

- (id<PlaynCoreLayer>)hitTestWithPlaynCoreLayer:(id<PlaynCoreLayer>)layer
                           withPythagorasFPoint:(PythagorasFPoint *)p {
  if ([((PythagorasFPoint *) NIL_CHK(p)) distanceWithFloat:[((id<PlaynCoreCanvasImage>) NIL_CHK(val$image_)) width] / 2 withFloat:[((id<PlaynCoreCanvasImage>) NIL_CHK(val$image_)) height] / 2] < this$0_.SPACING / 2.5f) return layer;
  return nil;
}

- (id)initWithTBNumberSelectScreen:(TBNumberSelectScreen *)outer$
          withPlaynCoreCanvasImage:(id<PlaynCoreCanvasImage>)capture$0 {
  if ((self = [super init])) {
    JreOperatorRetainedAssign(&this$0_, self, outer$);
    JreOperatorRetainedAssign(&val$image_, self, capture$0);
  }
  return self;
}

- (void)dealloc {
  JreOperatorRetainedAssign(&val$image_, self, nil);
  JreOperatorRetainedAssign(&this$0_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TBNumberSelectScreen_$3 *typedCopy = (TBNumberSelectScreen_$3 *) copy;
  typedCopy.this$0 = this$0_;
  typedCopy.val$image = val$image_;
}

@end
