//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/util/Frames.java
//
//  Created by Thomas on 7/1/13.
//

@protocol PlaynCoreImage;
@protocol PlaynCoreImageLayer;
@protocol PythagorasFIPoint;

#import "JreEmulation.h"

@protocol TripleplayUtilFrames < NSObject >
- (float)width;
- (float)height;
- (int)count;
- (id<PlaynCoreImage>)frameWithInt:(int)index;
- (id<PythagorasFIPoint>)offsetWithInt:(int)index;
- (void)applyWithInt:(int)index
withPlaynCoreImageLayer:(id<PlaynCoreImageLayer>)layer;
@end
