//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/util/TypedStorage.java
//
//  Created by Thomas on 7/1/13.
//

@class JavaLangBoolean;
@class JavaLangDouble;
@class JavaLangEnum;
@class JavaLangInteger;
@class JavaLangLong;
@class ReactRSet;
@class ReactValue;
@protocol PlaynCoreStorage;
@protocol ReactFunction;

#import "JreEmulation.h"
#import "react/RSet.h"
#import "react/Slot.h"

@interface TripleplayUtilTypedStorage : NSObject {
 @public
  id<PlaynCoreStorage> _storage_;
}

@property (nonatomic, retain) id<PlaynCoreStorage> _storage;

- (id)initWithPlaynCoreStorage:(id<PlaynCoreStorage>)storage;
- (BOOL)containsWithNSString:(NSString *)key;
- (NSString *)getWithNSString:(NSString *)key;
- (NSString *)getWithNSString:(NSString *)key
                 withNSString:(NSString *)defval;
- (void)setWithNSString:(NSString *)key
           withNSString:(NSString *)value;
- (int)getWithNSString:(NSString *)key
               withInt:(int)defval;
- (void)setWithNSString:(NSString *)key
                withInt:(int)value;
- (long long int)getWithNSString:(NSString *)key
                     withLongInt:(long long int)defval;
- (void)setWithNSString:(NSString *)key
            withLongInt:(long long int)value;
- (double)getWithNSString:(NSString *)key
               withDouble:(double)defval;
- (void)setWithNSString:(NSString *)key
             withDouble:(double)value;
- (BOOL)getWithNSString:(NSString *)key
               withBOOL:(BOOL)defval;
- (void)setWithNSString:(NSString *)key
               withBOOL:(BOOL)value;
- (id)getWithNSString:(NSString *)key
               withId:(JavaLangEnum *)defval;
- (void)setWithNSString:(NSString *)key
       withJavaLangEnum:(JavaLangEnum *)value;
- (void)removeWithNSString:(NSString *)key;
- (ReactValue *)valueForWithNSString:(NSString *)key
                        withNSString:(NSString *)defval;
- (ReactValue *)valueForWithNSString:(NSString *)key
                             withInt:(int)defval;
- (ReactValue *)valueForWithNSString:(NSString *)key
                         withLongInt:(long long int)defval;
- (ReactValue *)valueForWithNSString:(NSString *)key
                          withDouble:(double)defval;
- (ReactValue *)valueForWithNSString:(NSString *)key
                            withBOOL:(BOOL)defval;
- (ReactValue *)valueForWithNSString:(NSString *)key
                              withId:(JavaLangEnum *)defval;
- (ReactRSet *)setForWithNSString:(NSString *)key
                withReactFunction:(id<ReactFunction>)toFunc
                withReactFunction:(id<ReactFunction>)fromFunc;
@end

@interface TripleplayUtilTypedStorage_$1 : ReactSlot {
 @public
  TripleplayUtilTypedStorage *this$0_;
  NSString *val$key_;
}

@property (nonatomic, retain) TripleplayUtilTypedStorage *this$0;
@property (nonatomic, copy) NSString *val$key;

- (void)onEmitWithId:(NSString *)value;
- (id)initWithTripleplayUtilTypedStorage:(TripleplayUtilTypedStorage *)outer$
                            withNSString:(NSString *)capture$0;
@end

@interface TripleplayUtilTypedStorage_$2 : ReactSlot {
 @public
  TripleplayUtilTypedStorage *this$0_;
  NSString *val$key_;
}

@property (nonatomic, retain) TripleplayUtilTypedStorage *this$0;
@property (nonatomic, copy) NSString *val$key;

- (void)onEmitWithId:(JavaLangInteger *)value;
- (id)initWithTripleplayUtilTypedStorage:(TripleplayUtilTypedStorage *)outer$
                            withNSString:(NSString *)capture$0;
@end

@interface TripleplayUtilTypedStorage_$3 : ReactSlot {
 @public
  TripleplayUtilTypedStorage *this$0_;
  NSString *val$key_;
}

@property (nonatomic, retain) TripleplayUtilTypedStorage *this$0;
@property (nonatomic, copy) NSString *val$key;

- (void)onEmitWithId:(JavaLangLong *)value;
- (id)initWithTripleplayUtilTypedStorage:(TripleplayUtilTypedStorage *)outer$
                            withNSString:(NSString *)capture$0;
@end

@interface TripleplayUtilTypedStorage_$4 : ReactSlot {
 @public
  TripleplayUtilTypedStorage *this$0_;
  NSString *val$key_;
}

@property (nonatomic, retain) TripleplayUtilTypedStorage *this$0;
@property (nonatomic, copy) NSString *val$key;

- (void)onEmitWithId:(JavaLangDouble *)value;
- (id)initWithTripleplayUtilTypedStorage:(TripleplayUtilTypedStorage *)outer$
                            withNSString:(NSString *)capture$0;
@end

@interface TripleplayUtilTypedStorage_$5 : ReactSlot {
 @public
  TripleplayUtilTypedStorage *this$0_;
  NSString *val$key_;
}

@property (nonatomic, retain) TripleplayUtilTypedStorage *this$0;
@property (nonatomic, copy) NSString *val$key;

- (void)onEmitWithId:(JavaLangBoolean *)value;
- (id)initWithTripleplayUtilTypedStorage:(TripleplayUtilTypedStorage *)outer$
                            withNSString:(NSString *)capture$0;
@end

@interface TripleplayUtilTypedStorage_$6 : ReactSlot {
 @public
  TripleplayUtilTypedStorage *this$0_;
  NSString *val$key_;
}

@property (nonatomic, retain) TripleplayUtilTypedStorage *this$0;
@property (nonatomic, copy) NSString *val$key;

- (void)onEmitWithId:(JavaLangEnum *)value;
- (id)initWithTripleplayUtilTypedStorage:(TripleplayUtilTypedStorage *)outer$
                            withNSString:(NSString *)capture$0;
@end

@interface TripleplayUtilTypedStorage_$7 : ReactRSet_Listener {
 @public
  TripleplayUtilTypedStorage *this$0_;
  ReactRSet *val$rset_;
  id<ReactFunction> val$fromFunc_;
  NSString *val$key_;
}

@property (nonatomic, retain) TripleplayUtilTypedStorage *this$0;
@property (nonatomic, retain) ReactRSet *val$rset;
@property (nonatomic, retain) id<ReactFunction> val$fromFunc;
@property (nonatomic, copy) NSString *val$key;

- (void)onAddWithId:(id)unused;
- (id)initWithTripleplayUtilTypedStorage:(TripleplayUtilTypedStorage *)outer$
                           withReactRSet:(ReactRSet *)capture$0
                       withReactFunction:(id<ReactFunction>)capture$1
                            withNSString:(NSString *)capture$2;
@end
