//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/game/trans/InterpedTransition.java
//
//  Created by Thomas on 7/1/13.
//

@class TripleplayUtilInterpolator;

#import "JreEmulation.h"
#import "AbstractTransition.h"

@interface TripleplayGameTransInterpedTransition : TripleplayGameTransAbstractTransition {
 @public
  TripleplayUtilInterpolator *_interp_;
}

@property (nonatomic, retain) TripleplayUtilInterpolator *_interp;

- (id)linear;
- (id)easeIn;
- (id)easeOut;
- (id)easeInOut;
- (id)interpWithTripleplayUtilInterpolator:(TripleplayUtilInterpolator *)interp;
- (TripleplayUtilInterpolator *)defaultInterpolator;
- (id)init;
@end
