//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/ui/Style.java
//
//  Created by Thomas on 7/1/13.
//

@class JavaLangBoolean;
@class JavaLangInteger;
@class PlaynCoreTextFormat;
@class PlaynCoreTextFormat_AlignmentEnum;
@class TripleplayUiElement;
@class TripleplayUiStyle;
@class TripleplayUiStyle_Flag;
@class TripleplayUiStyle_HAlignStyle;
@class TripleplayUiStyle_PosStyle;
@class TripleplayUiStyle_TextEffectStyle;
@class TripleplayUiStyle_VAlignStyle;
@class TripleplayUtilEffectRenderer;

#import "JreEmulation.h"
#import "java/lang/Enum.h"

typedef enum {
  TripleplayUiStyle_Mode_DEFAULT = 0,
  TripleplayUiStyle_Mode_DISABLED = 1,
  TripleplayUiStyle_Mode_SELECTED = 2,
  TripleplayUiStyle_Mode_DISABLED_SELECTED = 3,
} TripleplayUiStyle_Mode;

@interface TripleplayUiStyle_ModeEnum : JavaLangEnum < NSCopying > {
}
+ (TripleplayUiStyle_ModeEnum *)DEFAULT;
+ (TripleplayUiStyle_ModeEnum *)DISABLED;
+ (TripleplayUiStyle_ModeEnum *)SELECTED;
+ (TripleplayUiStyle_ModeEnum *)DISABLED_SELECTED;
+ (IOSObjectArray *)values;
+ (TripleplayUiStyle_ModeEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end

@interface TripleplayUiStyle_Binding : NSObject {
 @public
  TripleplayUiStyle *style_;
  id value_;
}

@property (nonatomic, retain) TripleplayUiStyle *style;
@property (nonatomic, retain) id value;

- (id)initWithTripleplayUiStyle:(TripleplayUiStyle *)style
                         withId:(id)value;
@end

typedef enum {
  TripleplayUiStyle_HAlign_LEFT = 0,
  TripleplayUiStyle_HAlign_RIGHT = 1,
  TripleplayUiStyle_HAlign_CENTER = 2,
} TripleplayUiStyle_HAlign;

@interface TripleplayUiStyle_HAlignEnum : JavaLangEnum < NSCopying > {
}
+ (TripleplayUiStyle_HAlignEnum *)LEFT;
+ (TripleplayUiStyle_HAlignEnum *)RIGHT;
+ (TripleplayUiStyle_HAlignEnum *)CENTER;
+ (IOSObjectArray *)values;
+ (TripleplayUiStyle_HAlignEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (float)offsetWithFloat:(float)size
               withFloat:(float)extent;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end

@interface TripleplayUiStyle_HAlignEnum_$1 : TripleplayUiStyle_HAlignEnum {
}

- (float)offsetWithFloat:(float)size
               withFloat:(float)extent;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end

@interface TripleplayUiStyle_HAlignEnum_$2 : TripleplayUiStyle_HAlignEnum {
}

- (float)offsetWithFloat:(float)size
               withFloat:(float)extent;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end

@interface TripleplayUiStyle_HAlignEnum_$3 : TripleplayUiStyle_HAlignEnum {
}

- (float)offsetWithFloat:(float)size
               withFloat:(float)extent;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end

typedef enum {
  TripleplayUiStyle_VAlign_TOP = 0,
  TripleplayUiStyle_VAlign_BOTTOM = 1,
  TripleplayUiStyle_VAlign_CENTER = 2,
} TripleplayUiStyle_VAlign;

@interface TripleplayUiStyle_VAlignEnum : JavaLangEnum < NSCopying > {
}
+ (TripleplayUiStyle_VAlignEnum *)TOP;
+ (TripleplayUiStyle_VAlignEnum *)BOTTOM;
+ (TripleplayUiStyle_VAlignEnum *)CENTER;
+ (IOSObjectArray *)values;
+ (TripleplayUiStyle_VAlignEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (float)offsetWithFloat:(float)size
               withFloat:(float)extent;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end

@interface TripleplayUiStyle_VAlignEnum_$1 : TripleplayUiStyle_VAlignEnum {
}

- (float)offsetWithFloat:(float)size
               withFloat:(float)extent;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end

@interface TripleplayUiStyle_VAlignEnum_$2 : TripleplayUiStyle_VAlignEnum {
}

- (float)offsetWithFloat:(float)size
               withFloat:(float)extent;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end

@interface TripleplayUiStyle_VAlignEnum_$3 : TripleplayUiStyle_VAlignEnum {
}

- (float)offsetWithFloat:(float)size
               withFloat:(float)extent;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end

typedef enum {
  TripleplayUiStyle_Pos_LEFT = 0,
  TripleplayUiStyle_Pos_ABOVE = 1,
  TripleplayUiStyle_Pos_RIGHT = 2,
  TripleplayUiStyle_Pos_BELOW = 3,
} TripleplayUiStyle_Pos;

@interface TripleplayUiStyle_PosEnum : JavaLangEnum < NSCopying > {
}
+ (TripleplayUiStyle_PosEnum *)LEFT;
+ (TripleplayUiStyle_PosEnum *)ABOVE;
+ (TripleplayUiStyle_PosEnum *)RIGHT;
+ (TripleplayUiStyle_PosEnum *)BELOW;
+ (IOSObjectArray *)values;
+ (TripleplayUiStyle_PosEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end

typedef enum {
  TripleplayUiStyle_TextEffect_PIXEL_OUTLINE = 0,
  TripleplayUiStyle_TextEffect_VECTOR_OUTLINE = 1,
  TripleplayUiStyle_TextEffect_SHADOW = 2,
  TripleplayUiStyle_TextEffect_NONE = 3,
} TripleplayUiStyle_TextEffect;

@interface TripleplayUiStyle_TextEffectEnum : JavaLangEnum < NSCopying > {
}
+ (TripleplayUiStyle_TextEffectEnum *)PIXEL_OUTLINE;
+ (TripleplayUiStyle_TextEffectEnum *)VECTOR_OUTLINE;
+ (TripleplayUiStyle_TextEffectEnum *)SHADOW;
+ (TripleplayUiStyle_TextEffectEnum *)NONE;
+ (IOSObjectArray *)values;
+ (TripleplayUiStyle_TextEffectEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end

@interface TripleplayUiStyle : NSObject {
 @public
  BOOL inherited_;
}

@property (nonatomic, assign) BOOL inherited;

+ (TripleplayUiStyle *)COLOR;
+ (TripleplayUiStyle *)HIGHLIGHT;
+ (TripleplayUiStyle *)SHADOW;
+ (TripleplayUiStyle *)SHADOW_X;
+ (TripleplayUiStyle *)SHADOW_Y;
+ (TripleplayUiStyle *)OUTLINE_WIDTH;
+ (TripleplayUiStyle *)OUTLINE_CAP;
+ (TripleplayUiStyle *)OUTLINE_JOIN;
+ (TripleplayUiStyle_HAlignStyle *)HALIGN;
+ (TripleplayUiStyle_VAlignStyle *)VALIGN;
+ (TripleplayUiStyle *)FONT;
+ (TripleplayUiStyle_Flag *)TEXT_WRAP;
+ (TripleplayUiStyle_TextEffectStyle *)TEXT_EFFECT;
+ (TripleplayUiStyle_Flag *)UNDERLINE;
+ (TripleplayUiStyle *)BACKGROUND;
+ (TripleplayUiStyle_PosStyle *)ICON_POS;
+ (TripleplayUiStyle *)ICON_GAP;
+ (TripleplayUiStyle_Flag *)ICON_CUDDLE;
+ (TripleplayUiStyle *)ACTION_SOUND;
+ (PlaynCoreTextFormat *)createTextFormatWithTripleplayUiElement:(TripleplayUiElement *)elem;
+ (TripleplayUtilEffectRenderer *)createEffectRendererWithTripleplayUiElement:(TripleplayUiElement *)elem;
- (id)getDefaultWithTripleplayUiElement:(TripleplayUiElement *)mode;
- (TripleplayUiStyle_Binding *)isWithId:(id)value;
+ (TripleplayUiStyle *)newStyleWithBOOL:(BOOL)inherited
                                 withId:(id)defaultValue OBJC_METHOD_FAMILY_NONE;
+ (TripleplayUiStyle_Flag *)newFlagWithBOOL:(BOOL)inherited
                                   withBOOL:(BOOL)defaultValue OBJC_METHOD_FAMILY_NONE;
- (id)initWithBOOL:(BOOL)inherited;
+ (PlaynCoreTextFormat_AlignmentEnum *)toAlignmentWithTripleplayUiStyle_HAlignEnum:(TripleplayUiStyle_HAlignEnum *)align;
@end

@interface TripleplayUiStyle_HAlignStyle : TripleplayUiStyle {
 @public
  TripleplayUiStyle_Binding *left_;
  TripleplayUiStyle_Binding *right_;
  TripleplayUiStyle_Binding *center_;
}

@property (nonatomic, retain) TripleplayUiStyle_Binding *left;
@property (nonatomic, retain) TripleplayUiStyle_Binding *right;
@property (nonatomic, retain) TripleplayUiStyle_Binding *center;

- (TripleplayUiStyle_HAlignEnum *)getDefaultWithTripleplayUiElement:(TripleplayUiElement *)elem;
- (id)init;
@end

@interface TripleplayUiStyle_VAlignStyle : TripleplayUiStyle {
 @public
  TripleplayUiStyle_Binding *top_;
  TripleplayUiStyle_Binding *bottom_;
  TripleplayUiStyle_Binding *center_;
}

@property (nonatomic, retain) TripleplayUiStyle_Binding *top;
@property (nonatomic, retain) TripleplayUiStyle_Binding *bottom;
@property (nonatomic, retain) TripleplayUiStyle_Binding *center;

- (TripleplayUiStyle_VAlignEnum *)getDefaultWithTripleplayUiElement:(TripleplayUiElement *)elem;
- (id)init;
@end

@interface TripleplayUiStyle_PosStyle : TripleplayUiStyle {
 @public
  TripleplayUiStyle_Binding *left_;
  TripleplayUiStyle_Binding *above_;
  TripleplayUiStyle_Binding *right_;
  TripleplayUiStyle_Binding *below_;
}

@property (nonatomic, retain) TripleplayUiStyle_Binding *left;
@property (nonatomic, retain) TripleplayUiStyle_Binding *above;
@property (nonatomic, retain) TripleplayUiStyle_Binding *right;
@property (nonatomic, retain) TripleplayUiStyle_Binding *below;

- (TripleplayUiStyle_PosEnum *)getDefaultWithTripleplayUiElement:(TripleplayUiElement *)elem;
- (id)init;
@end

@interface TripleplayUiStyle_TextEffectStyle : TripleplayUiStyle {
 @public
  TripleplayUiStyle_Binding *outline_;
  TripleplayUiStyle_Binding *pixelOutline_;
  TripleplayUiStyle_Binding *vectorOutline_;
  TripleplayUiStyle_Binding *shadow_;
  TripleplayUiStyle_Binding *none_;
}

@property (nonatomic, retain) TripleplayUiStyle_Binding *outline;
@property (nonatomic, retain) TripleplayUiStyle_Binding *pixelOutline;
@property (nonatomic, retain) TripleplayUiStyle_Binding *vectorOutline;
@property (nonatomic, retain) TripleplayUiStyle_Binding *shadow;
@property (nonatomic, retain) TripleplayUiStyle_Binding *none;

- (TripleplayUiStyle_TextEffectEnum *)getDefaultWithTripleplayUiElement:(TripleplayUiElement *)elem;
- (id)init;
@end

@interface TripleplayUiStyle_Flag : TripleplayUiStyle {
 @public
  TripleplayUiStyle_Binding *off_;
  TripleplayUiStyle_Binding *on_;
  JavaLangBoolean *_default_;
}

@property (nonatomic, retain) TripleplayUiStyle_Binding *off;
@property (nonatomic, retain) TripleplayUiStyle_Binding *on;
@property (nonatomic, retain) JavaLangBoolean *_default;

- (id)initWithBOOL:(BOOL)inherited
          withBOOL:(BOOL)defaultVal;
- (JavaLangBoolean *)getDefaultWithTripleplayUiElement:(TripleplayUiElement *)mode;
@end

@interface TripleplayUiStyle_$1 : TripleplayUiStyle {
}

- (JavaLangInteger *)getDefaultWithTripleplayUiElement:(TripleplayUiElement *)elem;
- (id)initWithBOOL:(BOOL)arg$0;
@end

@interface TripleplayUiStyle_$2 : TripleplayUiStyle {
}

- (JavaLangInteger *)getDefaultWithTripleplayUiElement:(TripleplayUiElement *)elem;
- (id)initWithBOOL:(BOOL)arg$0;
@end

@interface TripleplayUiStyle_$3 : TripleplayUiStyle {
 @public
  id val$defaultValue_;
}

@property (nonatomic, retain) id val$defaultValue;

- (id)getDefaultWithTripleplayUiElement:(TripleplayUiElement *)elem;
- (id)initWithBOOL:(BOOL)arg$0
            withId:(id)capture$0;
@end
