//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/particle/effect/Move.java
//
//  Created by Thomas on 7/1/13.
//

#import "IOSFloatArray.h"
#import "ParticleBuffer.h"

@implementation TripleplayParticleEffectMove

- (void)applyWithInt:(int)index
withJavaLangFloatArray:(IOSFloatArray *)data
             withInt:(int)start
           withFloat:(float)now
           withFloat:(float)dt {
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_TX withFloat:[data floatAtIndex:start + TPParticleBuffer_TX] + [((IOSFloatArray *) NIL_CHK(data)) floatAtIndex:start + TPParticleBuffer_VEL_X] * dt];
  [((IOSFloatArray *) NIL_CHK(data)) replaceFloatAtIndex:start + TPParticleBuffer_TY withFloat:[data floatAtIndex:start + TPParticleBuffer_TY] + [((IOSFloatArray *) NIL_CHK(data)) floatAtIndex:start + TPParticleBuffer_VEL_Y] * dt];
}

- (id)init {
  return [super init];
}

- (void)dealloc {
  [super dealloc];
}

@end
