//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: react/AbstractValue.java
//
//  Created by Thomas on 7/1/13.
//

@protocol ReactConnection;
@protocol ReactFunction;

#import "JreEmulation.h"
#import "MappedValue.h"
#import "Reactor.h"
#import "ValueView.h"

@interface ReactAbstractValue : ReactReactor < ReactValueView > {
}

- (id<ReactValueView>)mapWithReactFunction:(id<ReactFunction>)func;
- (id<ReactConnection>)connectWithReactValueView_Listener:(ReactValueView_Listener *)listener;
- (id<ReactConnection>)connectNotifyWithReactValueView_Listener:(ReactValueView_Listener *)listener;
- (void)disconnectWithReactValueView_Listener:(ReactValueView_Listener *)listener;
- (NSUInteger)hash;
- (BOOL)isEqual:(id)other;
- (NSString *)description;
- (id)updateAndNotifyIfWithId:(id)value;
- (id)updateAndNotifyWithId:(id)value;
- (id)updateAndNotifyWithId:(id)value
                   withBOOL:(BOOL)force;
- (void)emitChangeWithId:(id)value
                  withId:(id)ovalue;
- (void)notifyChangeWithId:(id)value
                    withId:(id)ovalue;
- (id)updateLocalWithId:(id)value;
- (id)get;
- (id)init;
@end

@interface ReactAbstractValue_$1 : ReactMappedValue {
 @public
  id<ReactFunction> val$func_;
  ReactAbstractValue *val$outer_;
}

@property (nonatomic, retain) id<ReactFunction> val$func;
@property (nonatomic, retain) ReactAbstractValue *val$outer;

- (id)get;
- (id<ReactConnection>)connect;
- (id)initWithReactFunction:(id<ReactFunction>)capture$0
     withReactAbstractValue:(ReactAbstractValue *)capture$1;
@end

@interface ReactAbstractValue_$1_$1 : ReactValueView_Listener {
 @public
  ReactAbstractValue_$1 *this$0_;
}

@property (nonatomic, retain) ReactAbstractValue_$1 *this$0;

- (void)onChangeWithId:(id)value
                withId:(id)ovalue;
- (id)initWithReactAbstractValue_$1:(ReactAbstractValue_$1 *)outer$;
@end
