//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: react/ConnectionGroup.java
//
//  Created by Thomas on 7/1/13.
//

@protocol JavaUtilSet;
@protocol ReactConnection;

#import "JreEmulation.h"

@interface ReactConnectionGroup : NSObject {
 @public
  id<JavaUtilSet> _connections_;
}

@property (nonatomic, retain) id<JavaUtilSet> _connections;

- (void)disconnect;
- (id<ReactConnection>)addWithReactConnection:(id<ReactConnection>)c;
- (void)removeWithReactConnection:(id<ReactConnection>)c;
- (id)init;
@end
