//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: C:\Users\Thomas\Documents\Eclipse\Tux\tuxblocks\core\src\main\java\tuxkids\tuxblocks\core\defense\Pathing.java
//
//  Created by Thomas on 7/1/13.
//

@class IOSIntArray;
@class JavaUtilHashMap;
@class PythagorasIPoint;
@class TBDGrid;
@protocol JavaUtilList;

#import "JreEmulation.h"
#import "java/util/Comparator.h"

@interface TBDPathing : NSObject {
}

+ (IOSIntArray *)offRows;
+ (IOSIntArray *)offCols;
+ (id<JavaUtilList>)getPathWithTBDGrid:(TBDGrid *)grid
                  withPythagorasIPoint:(PythagorasIPoint *)from
                  withPythagorasIPoint:(PythagorasIPoint *)to;
+ (id<JavaUtilList>)reconstructPathWithJavaUtilHashMap:(JavaUtilHashMap *)cameFrom
                                  withPythagorasIPoint:(PythagorasIPoint *)currentNode;
- (id)init;
@end

typedef TBDPathing TuxkidsTuxblocksCoreDefensePathing;

@interface TBDPathing_$1 : NSObject < JavaUtilComparator > {
 @public
  JavaUtilHashMap *val$fScore_;
}

@property (nonatomic, retain) JavaUtilHashMap *val$fScore;

- (int)compareWithId:(PythagorasIPoint *)o1
              withId:(PythagorasIPoint *)o2;
- (BOOL)isEqual:(id)param0;
- (id)initWithJavaUtilHashMap:(JavaUtilHashMap *)capture$0;
@end
