//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java/tuxkids/tuxblocks/core/effect/anim/Animation.java
//
//  Created by Thomas on 7/10/13.
//

#import "IOSObjectArray.h"
#import "playn/core/Assets.h"
#import "playn/core/Image.h"
#import "tuxkids/tuxblocks/core/PlayNObject.h"
#import "tuxkids/tuxblocks/core/effect/anim/Animation.h"

@implementation TuxkidsTuxblocksCoreEffectAnimAnimation

@synthesize images = images_;

- (id)initWithNSString:(NSString *)folder
               withInt:(int)start
               withInt:(int)end
          withNSString:(NSString *)ext {
  if ((self = [super init])) {
    images_ = [[IOSObjectArray alloc] initWithLength:end - start + 1 type:[IOSClass classWithProtocol:@protocol(PlaynCoreImage)]];
    for (int i = start; i <= end; i++) {
      [((IOSObjectArray *) NIL_CHK(images_)) replaceObjectAtIndex:i - start withObject:[((id<PlaynCoreAssets>) [TuxkidsTuxblocksCorePlayNObject assets]) getImageWithNSString:[NSString stringWithFormat:@"anim/%@/%d.png", folder, i]]];
    }
  }
  return self;
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TuxkidsTuxblocksCoreEffectAnimAnimation *typedCopy = (TuxkidsTuxblocksCoreEffectAnimAnimation *) copy;
  typedCopy.images = images_;
}

@end
