//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: C:\Users\Thomas\Documents\Eclipse\Tux\tuxblocks\core\src\main\java\tuxkids\tuxblocks\core\solve\expression\Division.java
//
//  Created by Thomas on 7/1/13.
//

@class TBExpression;

#import "JreEmulation.h"
#import "tuxkids/tuxblocks/core/solve/expression/BinaryOperation.h"

@interface TBDivision : TBBinaryOperation {
}

- (id)initWithTBExpression:(TBExpression *)operandA
          withTBExpression:(TBExpression *)operandB;
- (int)operateWithInt:(int)a
              withInt:(int)b;
- (NSString *)getSymbol;
- (BOOL)isCommutative;
- (int)getPrecedence;
@end

typedef TBDivision TuxkidsTuxblocksCoreSolveExpressionDivision;
