//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: react/SignalView.java
//
//  Created by Thomas on 7/1/13.
//

@class ReactSlot;
@protocol ReactConnection;
@protocol ReactFunction;

#import "JreEmulation.h"

@protocol ReactSignalView < NSObject >
- (id<ReactSignalView>)mapWithReactFunction:(id<ReactFunction>)func;
- (id<ReactConnection>)connectWithReactSlot:(ReactSlot *)slot;
- (void)disconnectWithReactSlot:(ReactSlot *)slot;
@end
