//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java/tuxkids/tuxblocks/core/defense/tower/Freezer.java
//
//  Created by Thomas on 7/10/13.
//

@class TuxkidsTuxblocksCoreDefenseProjectileProjectile;
@class TuxkidsTuxblocksCoreDefenseWalkerWalker;

#import "JreEmulation.h"
#import "tuxkids/tuxblocks/core/defense/tower/Tower.h"

@interface TuxkidsTuxblocksCoreDefenseTowerFreezer : TuxkidsTuxblocksCoreDefenseTowerTower {
}

- (int)rows;
- (int)cols;
- (float)damage;
- (int)fireRate;
- (float)range;
- (TuxkidsTuxblocksCoreDefenseProjectileProjectile *)createProjectile;
- (TuxkidsTuxblocksCoreDefenseTowerTower *)copy__ OBJC_METHOD_FAMILY_NONE;
- (NSString *)name;
- (int)cost;
- (int)commonness;
- (float)splashRadius;
- (void)addBuffsWithTuxkidsTuxblocksCoreDefenseWalkerWalker:(TuxkidsTuxblocksCoreDefenseWalkerWalker *)walker;
- (id)init;
@end
