//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: tripleplay/ui/layout/AbsoluteLayout.java
//
//  Created by Thomas on 7/1/13.
//

#import "Asserts.h"
#import "Dimension.h"
#import "Element.h"
#import "Elements.h"
#import "IDimension.h"
#import "IPoint.h"
#import "Layout.h"
#import "Point.h"
#import "Rectangle.h"
#import "Style.h"
#import "java/util/Iterator.h"

@implementation TripleplayUiLayoutAbsoluteLayout

static PythagorasFDimension * TripleplayUiLayoutAbsoluteLayout_ZERO_;

+ (PythagorasFDimension *)ZERO {
  return TripleplayUiLayoutAbsoluteLayout_ZERO_;
}

+ (id)atWithId:(TripleplayUiElement *)elem
     withFloat:(float)x
     withFloat:(float)y {
  return ((TripleplayUiElement *) [TripleplayUiLayoutAbsoluteLayout atWithId:elem withPythagorasFIPoint:[[[PythagorasFPoint alloc] initWithFloat:x withFloat:y] autorelease]]);
}

+ (id)atWithId:(TripleplayUiElement *)elem
withPythagorasFIPoint:(id<PythagorasFIPoint>)position {
  return ((TripleplayUiElement *) [TripleplayUiLayoutAbsoluteLayout atWithId:elem withPythagorasFIPoint:position withPythagorasFIDimension:TripleplayUiLayoutAbsoluteLayout_ZERO_]);
}

+ (id)atWithId:(TripleplayUiElement *)elem
     withFloat:(float)x
     withFloat:(float)y
     withFloat:(float)width
     withFloat:(float)height {
  return ((TripleplayUiElement *) [TripleplayUiLayoutAbsoluteLayout atWithId:elem withPythagorasFIPoint:[[[PythagorasFPoint alloc] initWithFloat:x withFloat:y] autorelease] withPythagorasFIDimension:[[[PythagorasFDimension alloc] initWithFloat:width withFloat:height] autorelease]]);
}

+ (id)atWithId:(TripleplayUiElement *)elem
withPythagorasFIPoint:(id<PythagorasFIPoint>)position
withPythagorasFIDimension:(id<PythagorasFIDimension>)size {
  (void) [((TripleplayUiElement *) NIL_CHK(elem)) setConstraintWithTripleplayUiLayout_Constraint:[[[TripleplayUiLayoutAbsoluteLayout_Constraint alloc] initWithPythagorasFIPoint:position withPythagorasFIDimension:size withTripleplayUiStyle_HAlignEnum:[TripleplayUiStyle_HAlignEnum LEFT] withTripleplayUiStyle_VAlignEnum:[TripleplayUiStyle_VAlignEnum TOP]] autorelease]];
  return elem;
}

+ (id)atWithId:(TripleplayUiElement *)elem
     withFloat:(float)x
     withFloat:(float)y
withTripleplayUiStyle_HAlignEnum:(TripleplayUiStyle_HAlignEnum *)halign
withTripleplayUiStyle_VAlignEnum:(TripleplayUiStyle_VAlignEnum *)valign {
  return ((TripleplayUiElement *) [TripleplayUiLayoutAbsoluteLayout atWithId:elem withPythagorasFIPoint:[[[PythagorasFPoint alloc] initWithFloat:x withFloat:y] autorelease] withPythagorasFIDimension:TripleplayUiLayoutAbsoluteLayout_ZERO_ withTripleplayUiStyle_HAlignEnum:halign withTripleplayUiStyle_VAlignEnum:valign]);
}

+ (id)atWithId:(TripleplayUiElement *)elem
withPythagorasFIPoint:(id<PythagorasFIPoint>)position
withTripleplayUiStyle_HAlignEnum:(TripleplayUiStyle_HAlignEnum *)halign
withTripleplayUiStyle_VAlignEnum:(TripleplayUiStyle_VAlignEnum *)valign {
  return ((TripleplayUiElement *) [TripleplayUiLayoutAbsoluteLayout atWithId:elem withPythagorasFIPoint:position withPythagorasFIDimension:TripleplayUiLayoutAbsoluteLayout_ZERO_ withTripleplayUiStyle_HAlignEnum:halign withTripleplayUiStyle_VAlignEnum:valign]);
}

+ (id)atWithId:(TripleplayUiElement *)elem
     withFloat:(float)x
     withFloat:(float)y
     withFloat:(float)width
     withFloat:(float)height
withTripleplayUiStyle_HAlignEnum:(TripleplayUiStyle_HAlignEnum *)halign
withTripleplayUiStyle_VAlignEnum:(TripleplayUiStyle_VAlignEnum *)valign {
  return ((TripleplayUiElement *) [TripleplayUiLayoutAbsoluteLayout atWithId:elem withPythagorasFIPoint:[[[PythagorasFPoint alloc] initWithFloat:x withFloat:y] autorelease] withPythagorasFIDimension:[[[PythagorasFDimension alloc] initWithFloat:width withFloat:height] autorelease] withTripleplayUiStyle_HAlignEnum:halign withTripleplayUiStyle_VAlignEnum:valign]);
}

+ (id)atWithId:(TripleplayUiElement *)elem
withPythagorasFIPoint:(id<PythagorasFIPoint>)position
withPythagorasFIDimension:(id<PythagorasFIDimension>)size
withTripleplayUiStyle_HAlignEnum:(TripleplayUiStyle_HAlignEnum *)halign
withTripleplayUiStyle_VAlignEnum:(TripleplayUiStyle_VAlignEnum *)valign {
  (void) [((TripleplayUiElement *) NIL_CHK(elem)) setConstraintWithTripleplayUiLayout_Constraint:[[[TripleplayUiLayoutAbsoluteLayout_Constraint alloc] initWithPythagorasFIPoint:position withPythagorasFIDimension:size withTripleplayUiStyle_HAlignEnum:halign withTripleplayUiStyle_VAlignEnum:valign] autorelease]];
  return elem;
}

+ (id)centerAtWithId:(TripleplayUiElement *)elem
           withFloat:(float)x
           withFloat:(float)y {
  return ((TripleplayUiElement *) [TripleplayUiLayoutAbsoluteLayout centerAtWithId:elem withPythagorasFIPoint:[[[PythagorasFPoint alloc] initWithFloat:x withFloat:y] autorelease]]);
}

+ (id)centerAtWithId:(TripleplayUiElement *)elem
withPythagorasFIPoint:(id<PythagorasFIPoint>)position {
  (void) [((TripleplayUiElement *) NIL_CHK(elem)) setConstraintWithTripleplayUiLayout_Constraint:[[[TripleplayUiLayoutAbsoluteLayout_Constraint alloc] initWithPythagorasFIPoint:position withPythagorasFIDimension:TripleplayUiLayoutAbsoluteLayout_ZERO_ withTripleplayUiStyle_HAlignEnum:[TripleplayUiStyle_HAlignEnum CENTER] withTripleplayUiStyle_VAlignEnum:[TripleplayUiStyle_VAlignEnum CENTER]] autorelease]];
  return elem;
}

- (PythagorasFDimension *)computeSizeWithTripleplayUiElements:(TripleplayUiElements *)elems
                                                    withFloat:(float)hintX
                                                    withFloat:(float)hintY {
  PythagorasFRectangle *bounds = [[[PythagorasFRectangle alloc] init] autorelease];
  {
    id<JavaUtilIterator> iter__ = ((id<JavaUtilIterator>) [((TripleplayUiElements *) NIL_CHK(elems)) iterator]);
    while ([((id<JavaUtilIterator>) NIL_CHK(iter__)) hasNext]) {
      TripleplayUiElement *elem = ((TripleplayUiElement *) [((id<JavaUtilIterator>) NIL_CHK(iter__)) next]);
      if (![((TripleplayUiElement *) NIL_CHK(elem)) isVisible]) continue;
      TripleplayUiLayoutAbsoluteLayout_Constraint *c = [TripleplayUiLayoutAbsoluteLayout constraintWithTripleplayUiElement:elem];
      id<PythagorasFIDimension> psize = [((TripleplayUiLayoutAbsoluteLayout_Constraint *) NIL_CHK(c)) psizeWithTripleplayUiLayoutAbsoluteLayout:self withTripleplayUiElement:elem];
      [((PythagorasFRectangle *) NIL_CHK(bounds)) addWithPythagorasFIRectangle:[[[PythagorasFRectangle alloc] initWithPythagorasFIPoint:[((TripleplayUiLayoutAbsoluteLayout_Constraint *) NIL_CHK(c)) posWithPythagorasFIDimension:psize] withPythagorasFIDimension:psize] autorelease]];
    }
  }
  return [[[PythagorasFDimension alloc] initWithFloat:((PythagorasFRectangle *) NIL_CHK(bounds)).width_ withFloat:((PythagorasFRectangle *) NIL_CHK(bounds)).height_] autorelease];
}

- (void)layoutWithTripleplayUiElements:(TripleplayUiElements *)elems
                             withFloat:(float)left
                             withFloat:(float)top
                             withFloat:(float)width
                             withFloat:(float)height {
  {
    id<JavaUtilIterator> iter__ = ((id<JavaUtilIterator>) [((TripleplayUiElements *) NIL_CHK(elems)) iterator]);
    while ([((id<JavaUtilIterator>) NIL_CHK(iter__)) hasNext]) {
      TripleplayUiElement *elem = ((TripleplayUiElement *) [((id<JavaUtilIterator>) NIL_CHK(iter__)) next]);
      if (![((TripleplayUiElement *) NIL_CHK(elem)) isVisible]) continue;
      TripleplayUiLayoutAbsoluteLayout_Constraint *c = [TripleplayUiLayoutAbsoluteLayout constraintWithTripleplayUiElement:elem];
      id<PythagorasFIDimension> psize = [((TripleplayUiLayoutAbsoluteLayout_Constraint *) NIL_CHK(c)) psizeWithTripleplayUiLayoutAbsoluteLayout:self withTripleplayUiElement:elem];
      id<PythagorasFIPoint> pos = [((TripleplayUiLayoutAbsoluteLayout_Constraint *) NIL_CHK(c)) posWithPythagorasFIDimension:psize];
      [self setBoundsWithTripleplayUiElement:elem withFloat:left + [((id<PythagorasFIPoint>) NIL_CHK(pos)) x] withFloat:top + [((id<PythagorasFIPoint>) NIL_CHK(pos)) y] withFloat:[((id<PythagorasFIDimension>) NIL_CHK(psize)) width] withFloat:[((id<PythagorasFIDimension>) NIL_CHK(psize)) height]];
    }
  }
}

+ (TripleplayUiLayoutAbsoluteLayout_Constraint *)constraintWithTripleplayUiElement:(TripleplayUiElement *)elem {
  return (TripleplayUiLayoutAbsoluteLayout_Constraint *) ((TripleplayUiLayout_Constraint *) [PlaynCoreAsserts checkNotNullWithId:[((TripleplayUiElement *) NIL_CHK(elem)) constraint] withId:@"Elements in AbsoluteLayout must have a constraint."]);
}

- (id)init {
  return [super init];
}

+ (void)initialize {
  if (self == [TripleplayUiLayoutAbsoluteLayout class]) {
    JreOperatorRetainedAssign(&TripleplayUiLayoutAbsoluteLayout_ZERO_, self, [[[PythagorasFDimension alloc] initWithFloat:0 withFloat:0] autorelease]);
  }
}

- (void)dealloc {
  [super dealloc];
}

@end
@implementation TripleplayUiLayoutAbsoluteLayout_Constraint

- (id<PythagorasFIPoint>)position {
  return position_;
}
- (void)setPosition:(id<PythagorasFIPoint>)position {
  JreOperatorRetainedAssign(&position_, self, position);
}
@synthesize position = position_;
- (id<PythagorasFIDimension>)size {
  return size_;
}
- (void)setSize:(id<PythagorasFIDimension>)size {
  JreOperatorRetainedAssign(&size_, self, size);
}
@synthesize size = size_;
- (TripleplayUiStyle_HAlignEnum *)halign {
  return halign_;
}
- (void)setHalign:(TripleplayUiStyle_HAlignEnum *)halign {
  JreOperatorRetainedAssign(&halign_, self, halign);
}
@synthesize halign = halign_;
- (TripleplayUiStyle_VAlignEnum *)valign {
  return valign_;
}
- (void)setValign:(TripleplayUiStyle_VAlignEnum *)valign {
  JreOperatorRetainedAssign(&valign_, self, valign);
}
@synthesize valign = valign_;

- (id)initWithPythagorasFIPoint:(id<PythagorasFIPoint>)position
      withPythagorasFIDimension:(id<PythagorasFIDimension>)size
withTripleplayUiStyle_HAlignEnum:(TripleplayUiStyle_HAlignEnum *)halign
withTripleplayUiStyle_VAlignEnum:(TripleplayUiStyle_VAlignEnum *)valign {
  if ((self = [super init])) {
    self.position = position;
    self.size = size;
    self.halign = halign;
    self.valign = valign;
  }
  return self;
}

- (id<PythagorasFIDimension>)psizeWithTripleplayUiLayoutAbsoluteLayout:(TripleplayUiLayoutAbsoluteLayout *)layout
                                               withTripleplayUiElement:(TripleplayUiElement *)elem {
  float fwidth = [((id<PythagorasFIDimension>) NIL_CHK(size_)) width], fheight = [((id<PythagorasFIDimension>) NIL_CHK(size_)) height];
  if (fwidth > 0 && fheight > 0) return size_;
  id<PythagorasFIDimension> psize = [((TripleplayUiLayoutAbsoluteLayout *) NIL_CHK(layout)) preferredSizeWithTripleplayUiElement:elem withFloat:fwidth withFloat:fheight];
  if (fwidth > 0) return [[[PythagorasFDimension alloc] initWithFloat:fwidth withFloat:[((id<PythagorasFIDimension>) NIL_CHK(psize)) height]] autorelease];
  else if (fheight > 0) return [[[PythagorasFDimension alloc] initWithFloat:[((id<PythagorasFIDimension>) NIL_CHK(psize)) width] withFloat:fheight] autorelease];
  else return psize;
}

- (id<PythagorasFIPoint>)posWithPythagorasFIDimension:(id<PythagorasFIDimension>)psize {
  return [[[PythagorasFPoint alloc] initWithFloat:[((id<PythagorasFIPoint>) NIL_CHK(position_)) x] + [((TripleplayUiStyle_HAlignEnum *) NIL_CHK(halign_)) offsetWithFloat:[((id<PythagorasFIDimension>) NIL_CHK(psize)) width] withFloat:0] withFloat:[((id<PythagorasFIPoint>) NIL_CHK(position_)) y] + [((TripleplayUiStyle_VAlignEnum *) NIL_CHK(valign_)) offsetWithFloat:[((id<PythagorasFIDimension>) NIL_CHK(psize)) height] withFloat:0]] autorelease];
}

- (void)dealloc {
  JreOperatorRetainedAssign(&valign_, self, nil);
  JreOperatorRetainedAssign(&halign_, self, nil);
  JreOperatorRetainedAssign(&size_, self, nil);
  JreOperatorRetainedAssign(&position_, self, nil);
  [super dealloc];
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  TripleplayUiLayoutAbsoluteLayout_Constraint *typedCopy = (TripleplayUiLayoutAbsoluteLayout_Constraint *) copy;
  typedCopy.position = position_;
  typedCopy.size = size_;
  typedCopy.halign = halign_;
  typedCopy.valign = valign_;
}

@end
