//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/util/SingularMatrixException.java
//
//  Created by Thomas on 7/1/13.
//

#import "JreEmulation.h"
#import "java/lang/RuntimeException.h"

@interface PythagorasUtilSingularMatrixException : JavaLangRuntimeException {
}

- (id)init;
- (id)initWithNSString:(NSString *)message;
@end
