//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/f/AbstractPoint.java
//
//  Created by Thomas on 7/9/13.
//

#import "pythagoras/f/FloatMath.h"
#import "pythagoras/f/IPoint.h"
#import "pythagoras/f/Point.h"
#import "pythagoras/f/Points.h"
#import "pythagoras/f/XY.h"
#import "pythagoras/util/Platform.h"
#import "AbstractPoint.h"

@implementation PythagorasFAbstractPoint

- (float)distanceSqWithFloat:(float)px
                   withFloat:(float)py {
  return [PythagorasFPoints distanceSqWithFloat:[self x] withFloat:[self y] withFloat:px withFloat:py];
}

- (float)distanceSqWithPythagorasFIPoint:(id<PythagorasFIPoint>)p {
  return [PythagorasFPoints distanceSqWithFloat:[self x] withFloat:[self y] withFloat:[((id<PythagorasFIPoint>) NIL_CHK(p)) x] withFloat:[((id<PythagorasFIPoint>) NIL_CHK(p)) y]];
}

- (float)distanceWithFloat:(float)px
                 withFloat:(float)py {
  return [PythagorasFPoints distanceWithFloat:[self x] withFloat:[self y] withFloat:px withFloat:py];
}

- (float)distanceWithPythagorasFIPoint:(id<PythagorasFIPoint>)p {
  return [PythagorasFPoints distanceWithFloat:[self x] withFloat:[self y] withFloat:[((id<PythagorasFIPoint>) NIL_CHK(p)) x] withFloat:[((id<PythagorasFIPoint>) NIL_CHK(p)) y]];
}

- (float)directionWithPythagorasFIPoint:(id<PythagorasFIPoint>)other {
  return [PythagorasFFloatMath atan2WithFloat:[((id<PythagorasFIPoint>) NIL_CHK(other)) y] - [self y] withFloat:[((id<PythagorasFIPoint>) NIL_CHK(other)) x] - [self x]];
}

- (PythagorasFPoint *)multWithFloat:(float)s {
  return [self multWithFloat:s withPythagorasFPoint:[[[PythagorasFPoint alloc] init] autorelease]];
}

- (PythagorasFPoint *)multWithFloat:(float)s
               withPythagorasFPoint:(PythagorasFPoint *)result {
  return [((PythagorasFPoint *) NIL_CHK(result)) setWithFloat:[self x] * s withFloat:[self y] * s];
}

- (PythagorasFPoint *)addWithFloat:(float)x
                         withFloat:(float)y {
  return [[[PythagorasFPoint alloc] initWithFloat:[self x] + x withFloat:[self y] + y] autorelease];
}

- (PythagorasFPoint *)addWithFloat:(float)x
                         withFloat:(float)y
              withPythagorasFPoint:(PythagorasFPoint *)result {
  return [((PythagorasFPoint *) NIL_CHK(result)) setWithFloat:[self x] + x withFloat:[self y] + y];
}

- (PythagorasFPoint *)subtractWithFloat:(float)x
                              withFloat:(float)y {
  return [self subtractWithFloat:x withFloat:y withPythagorasFPoint:[[[PythagorasFPoint alloc] init] autorelease]];
}

- (PythagorasFPoint *)subtractWithFloat:(float)x
                              withFloat:(float)y
                   withPythagorasFPoint:(PythagorasFPoint *)result {
  return [((PythagorasFPoint *) NIL_CHK(result)) setWithFloat:[self x] - x withFloat:[self y] - y];
}

- (PythagorasFPoint *)subtractWithPythagorasFIPoint:(id<PythagorasFIPoint>)other
                               withPythagorasFPoint:(PythagorasFPoint *)result {
  return [self subtractWithFloat:[((id<PythagorasFIPoint>) NIL_CHK(other)) x] withFloat:[((id<PythagorasFIPoint>) NIL_CHK(other)) y] withPythagorasFPoint:result];
}

- (PythagorasFPoint *)rotateWithFloat:(float)angle {
  return [self rotateWithFloat:angle withPythagorasFPoint:[[[PythagorasFPoint alloc] init] autorelease]];
}

- (PythagorasFPoint *)rotateWithFloat:(float)angle
                 withPythagorasFPoint:(PythagorasFPoint *)result {
  float x = [self x], y = [self y];
  float sina = [PythagorasFFloatMath sinWithFloat:angle], cosa = [PythagorasFFloatMath cosWithFloat:angle];
  return [((PythagorasFPoint *) NIL_CHK(result)) setWithFloat:x * cosa - y * sina withFloat:x * sina + y * cosa];
}

- (PythagorasFPoint *)clone {
  return [[[PythagorasFPoint alloc] initWithPythagorasFIPoint:self] autorelease];
}

- (BOOL)isEqual:(id)obj {
  if (obj == self) {
    return YES;
  }
  if ([obj isKindOfClass:[PythagorasFAbstractPoint class]]) {
    PythagorasFAbstractPoint *p = (PythagorasFAbstractPoint *) obj;
    return [self x] == [((PythagorasFAbstractPoint *) NIL_CHK(p)) x] && [self y] == [((PythagorasFAbstractPoint *) NIL_CHK(p)) y];
  }
  return NO;
}

- (NSUInteger)hash {
  return [PythagorasUtilPlatform hashCodeWithFloat:[self x]] ^ [PythagorasUtilPlatform hashCodeWithFloat:[self y]];
}

- (NSString *)description {
  return [PythagorasFPoints pointToStringWithFloat:[self x] withFloat:[self y]];
}

- (float)x {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (float)y {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id)init {
  return [super init];
}

- (id)copyWithZone:(NSZone *)zone {
  return [[self clone] retain];
}

- (void)dealloc {
  [super dealloc];
}

@end
