//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/f/FloatMath.java
//
//  Created by Thomas on 7/1/13.
//

#import "JreEmulation.h"
#import "MathUtil.h"

#define PythagorasFFloatMath_E 2.7182817
#define PythagorasFFloatMath_PI 3.1415927

@interface PythagorasFFloatMath : PythagorasFMathUtil {
}

+ (float)PI;
+ (float)E;
+ (float)sinWithFloat:(float)a;
+ (float)cosWithFloat:(float)a;
+ (float)tanWithFloat:(float)a;
+ (float)asinWithFloat:(float)a;
+ (float)acosWithFloat:(float)a;
+ (float)atanWithFloat:(float)a;
+ (float)atan2WithFloat:(float)y
              withFloat:(float)x;
+ (float)toDegreesWithFloat:(float)a;
+ (float)toRadiansWithFloat:(float)a;
+ (float)sqrtWithFloat:(float)v;
+ (float)cbrtWithFloat:(float)v;
+ (float)hypotWithFloat:(float)x
              withFloat:(float)y;
+ (float)expWithFloat:(float)v;
+ (float)logWithFloat:(float)v;
+ (float)log10WithFloat:(float)v;
+ (float)powWithFloat:(float)v
            withFloat:(float)e;
+ (float)floorWithFloat:(float)v;
+ (float)ceilWithFloat:(float)v;
- (id)init;
@end
