//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/i/Dimensions.java
//
//  Created by Thomas on 7/9/13.
//

#import "JreEmulation.h"

@interface PythagorasIDimensions : NSObject {
}

+ (NSString *)dimenToStringWithInt:(int)width
                           withInt:(int)height;
- (id)init;
@end
