//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: pythagoras/i/Point.java
//
//  Created by Thomas on 7/1/13.
//

@protocol PythagorasIIPoint;

#import "JreEmulation.h"
#import "AbstractPoint.h"
#import "java/io/Serializable.h"

@interface PythagorasIPoint : PythagorasIAbstractPoint < JavaIoSerializable > {
 @public
  int x__;
  int y__;
}

@property (nonatomic, assign) int x_;
@property (nonatomic, assign) int y_;

- (id)init;
- (id)initWithInt:(int)x
          withInt:(int)y;
- (id)initWithPythagorasIIPoint:(id<PythagorasIIPoint>)p;
- (void)setLocationWithPythagorasIIPoint:(id<PythagorasIIPoint>)p;
- (void)setLocationWithInt:(int)x
                   withInt:(int)y;
- (void)moveWithInt:(int)x
            withInt:(int)y;
- (void)translateWithInt:(int)dx
                 withInt:(int)dy;
- (int)x;
- (int)y;
@end
